### ISSUE TITLE
Gramine Package is not getting updated from v1.3.1 to  v1.4

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1185] opened 2023-02-16 09:00 UTC
### Description of the problem

This issue seen on focal:
When you try to do apt update on the system which already have gramine packages installed, it fails with below error message

```
Running apt-get update...
E: Repository 'https://packages.gramineproject.io focal InRelease' changed its 'Label' value from 'Gramine for focal' to 'Gramine'
# [error] Failed to add trusted package signing keys
```

When you disable the repo and enable it back after apt-update, it shows 3 packages can be updated, but it does not upgrade

```
Fetched 226 kB in 1s (257 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

```
gramineval3@gramineval3:~/anjali/mariadb_contrib/Curated-Apps$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  gramine-dcap gramine-ratls-dcap gramine-ratls-epid
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

```
gramineval3@gramineval3:~/anjali/mariadb_contrib/Curated-Apps$ sudo apt list --upgradable
Listing... Done
gramine-dcap/focal 1.4 amd64 [upgradable from: 1.3.1-1~ubuntu0.18.04]
gramine-ratls-dcap/focal 1.4 amd64 [upgradable from: 1.3.1-1~ubuntu0.18.04]
gramine-ratls-epid/focal 1.4 amd64 [upgradable from: 1.3.1-1~ubuntu0.18.04]
gramineval3@gramineval3:~/anjali/mariadb_contrib/Curated-Apps$

```

**Whereas in bionic, it asks user, do you want to continue and it continues to install new packages and upgrade it to v1.4**
```
E: Repository 'https://packages.gramineproject.io bionic InRelease' changed its 'Label' value from 'Gramine for bionic' to 'Gramine'
N: Repository 'https://packages.gramineproject.io bionic InRelease' changed its 'Version' value from '1.3~bionic' to '1.4'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]

```

### Expected results

Apt update should be successful. No error message should be seen

**Comment by dimakuv** [comment] 2023-02-16 09:56
Summoning @woju

**Comment by jkr0103** [comment] 2023-02-17 05:40
I faced the similar errors:
```
$ sudo curl -fsSLo /usr/share/keyrings/gramine-keyring.gpg https://packages.gramineproject.io/gramine-keyring.gpg
graminejk1@graminejk1:~$ sudo curl -fsSLo /usr/share/keyrings/intel-sgx-deb.asc https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
$ echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-sgx-deb.asc] https://download.01.org/intel-sgx/sgx_repo/ubuntu $(lsb_release -sc) main" \
> | sudo tee /etc/apt/sources.list.d/intel-sgx.list
deb [arch=amd64 signed-by=/usr/share/keyrings/intel-sgx-deb.asc] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main
$ sudo apt-get update
Hit:1 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Hit:2 https://download.docker.com/linux/ubuntu focal InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Get:4 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:5 https://download.01.org/intel-sgx/sgx_repo/ubuntu focal InRelease
Get:6 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:7 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2384 kB]
Get:9 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal InRelease [17.5 kB]
Get:10 https://packages.gramineproject.io focal InRelease [1858 B]
Get:11 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main amd64 Packages [38.4 kB]
Reading package lists... Done
E: Repository 'https://packages.gramineproject.io focal InRelease' changed its 'Label' value from 'Gramine for focal' to 'Gramine'
N: Repository 'https://packages.gramineproject.io focal InRelease' changed its 'Version' value from '1.3~focal' to '1.4'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
$
```
After this I opened the below files to check if anything is wrong here and closed without any changes:

```
$ vim /etc/apt/sources.list.d/gramine.list
$ vim /etc/apt/sources.list.d/intel-sgx.list

```
After that I tried `sudo apt update` again. This time along with error/warning, it gave option to accept the changes:

```
E: Repository 'https://packages.gramineproject.io bionic InRelease' changed its 'Label' value from 'Gramine for bionic' to 'Gramine'
N: Repository 'https://packages.gramineproject.io bionic InRelease' changed its 'Version' value from '1.3~bionic' to '1.4'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]
```
With that update and after that `sudo apt upgrage` went fine without any issues.

It seems opening and closing the `/etc/apt/sources.list.d/gramine.list` file fixed something.

**Comment by anjalirai-intel** [comment] 2023-02-20 06:29
While doing this experiment with @jkr0103 , I also realised that I have opened the file before doing apt-get update, to ensure the gramine repo is mounted correctly. 

So I did this experiment again on 18.04 system, where I did cat operation to see what gramine repo path is referring to, 
In this 18.04 apt-update did not failed, but it did throw error **"N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details."** and it did not upgrade the gramine packages

**cat /etc/apt/sources.list.d/gramine.list**
`deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ bionic main`

**intel@intel-Ice-Lake-Client-Platform:~$ sudo apt-get update**
```
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://in.archive.ubuntu.com/ubuntu bionic InRelease
Get:3 https://deb.nodesource.com/node_14.x bionic InRelease [4,584 B]
Hit:4 https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic InRelease
Get:5 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 https://packages.gramineproject.io bionic InRelease [1,860 B]
Get:7 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,569 kB]
Get:9 http://in.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,901 kB]
Get:10 https://deb.nodesource.com/node_14.x bionic/main amd64 Packages [776 B]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [1,318 kB]
Get:12 http://in.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [1,608 kB]
Get:13 http://in.archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [297 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [76.8 kB]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [1,060 kB]
Get:16 http://in.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [1,647 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,270 kB]
Get:18 http://in.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,882 kB]
Get:19 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [61.1 kB]
Get:20 http://in.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [302 kB]
Get:21 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 DEP-11 Metadata [2,464 B]
Get:22 http://in.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 DEP-11 Metadata [2,468 B]
Get:23 http://in.archive.ubuntu.com/ubuntu bionic-backports/main amd64 DEP-11 Metadata [8,120 B]
Get:24 http://in.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 DEP-11 Metadata [10.0 kB]
Reading package lists... Done
E: Repository 'https://packages.gramineproject.io bionic InRelease' changed its 'Label' value from 'Gramine for bionic' to 'Gramine'
N: Repository 'https://packages.gramineproject.io bionic InRelease' changed its 'Version' value from '1.3~bionic' to '1.4'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

```

Gramine packages is not listed under upgrade packages
**sudo apt-get upgrade**
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-hwe-5.4-headers-5.4.0-136 linux-hwe-5.4-headers-5.4.0-137
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  python3-software-properties software-properties-common software-properties-gtk
The following packages will be upgraded:
  firefox firefox-locale-en grub-efi-amd64-bin grub-efi-amd64-signed libsgx-ae-epid libsgx-ae-le libsgx-ae-pce
  libsgx-aesm-ecdsa-plugin libsgx-aesm-epid-plugin libsgx-aesm-launch-plugin libsgx-aesm-pce-plugin
  libsgx-aesm-quote-ex-plugin libsgx-enclave-common libsgx-epid libsgx-headers libsgx-launch libsgx-quote-ex
  libsgx-quote-ex-dev libsgx-uae-service libsgx-urts nodejs python-apt-common python3-apt sgx-aesm-service snapd
  ubuntu-advantage-tools update-notifier update-notifier-common
28 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Need to get 130 MB of archives.
After this operation, 1,933 kB of additional disk space will be used.
Do you want to continue? [Y/n] y

```

**Comment by woju** [comment] 2023-02-20 21:15
> `E: Repository 'https://packages.gramineproject.io bionic InRelease' changed its 'Label' value from 'Gramine for bionic' to 'Gramine'`

The problem is that, among other things I did while rearranging repos for 1.4 release (like retirement of `stable`), I've changed `Label:` metadata field in the repos. This was a mistake (I should have changed only for new repos, leave existing ones alone and just wait for their retirement). But now it's equally impossible to roll this back, because if I changed it, people who currently have those configured will see this error.

`apt` errors on this change of `Label:`, because if people have configured something using apt "preferences" (https://manpages.debian.org/bullseye/apt/apt_preferences.5.en.html), those preferences might become invalid, so they require manual intervention (or at least check if they are still OK).

So the solution is for people to run once `apt-get update --allow-releaseinfo-change` (after that, they can go back to running unqualified `apt-get update` as usual). People who didn't touch `apt.preferences.d` can do this safely, and people who did probably already know what's going on and don't need this explanation.

For this reason I think we should do an errata to release notes to warn people about this, and obviously forward this `apt-get update --allow-releaseinfo-change` solution to anyone affected. But unfortunately I can't fix this without breaking this for some other people.

**Comment by jinengandhi-intel** [comment] 2023-02-21 05:00
Commands ran:

1. `sudo apt-get update --allow-releaseinfo-change` --> With this command I still see the following message but no longer as errors.
```
N: Repository 'https://packages.gramineproject.io bionic InRelease' changed its 'Label' value from 'Gramine for bionic' to 'Gramine'
N: Repository 'https://packages.gramineproject.io bionic InRelease' changed its 'Version' value from '1.3~bionic' to '1.4'
```
2. `sudo apt-get update` --> this command runs fine without any errors.
3. `sudo apt-get --with-new-pkgs -y upgrade` --> this command now successfully upgrades gramine to v1.4. You would already be aware of this but just an FYI a plain `sudo apt-get upgrade` command does not upgrade the package, instead it says `The following packages have been kept back gramine gramine-ratls-dcap gramine-ratls-epid`

**Comment by dimakuv** [comment] 2023-02-21 08:59
> For this reason I think we should do an errata to release notes to warn people about this, and obviously forward this `apt-get update --allow-releaseinfo-change` solution to anyone affected. But unfortunately I can't fix this without breaking this for some other people.

@woju Could you do it then? Looks reasonable.

**Comment by woju** [comment] 2023-02-21 09:58
@mkow ^ WDYT?

**Comment by woju** [comment] 2023-02-21 14:24
I've updated the release notes.

**Closed by woju** 2023-02-21 14:24 UTC

**Comment by mkow** [comment] 2023-02-27 16:17
@woju: something looks wrong there, it says `apt-get update --allow- && [...]`.

**Comment by woju** [comment] 2023-02-27 17:14
Fixed. I wonder what happened, I'm fairly certain I wrote this correctly.
