### ISSUE TITLE
Error starting secret provisioning server. 

### ISSUE THREAD

**Issue by arkish** [gramineproject/gramine#1200] opened 2023-02-23 07:30 UTC
Followed steps to start secret provisioning server locally as per documentation.
Executed `./server_dcap ./files/wrap_key`

**result**
```--- Reading the master key for encrypted files from './files/wrap_key' ---
--- Starting the Secret Provisioning server on port 4433 ---
secret_provision_start_server: Secret Provisioning failed during mbedtls_x509_crt_parse_file with error -15872
[error] secret_provision_start_server() returned -1
```
Any suggestions on how to resolve this?

**Comment by dimakuv** [comment] 2023-02-23 07:58
The `ra-tls-secret-prov` example creates X.509 certificate (plus corresponding private key) on the fly, when you build using Make: https://github.com/gramineproject/gramine/blob/9eff514112d9ca5398e0575c80e524e55a6a9a88/CI-Examples/ra-tls-secret-prov/Makefile#L39-L47

The error `-15872` is the `MBEDTLS_ERR_PK_FILE_IO_ERROR` error, which signals that the certificate file (created under `ssl/server.crt`) cannot be read. My guess is that you created it with wrong permissions, e.g. you run Make under `sudo`?

Please show the output of `ls -la ssl/`.

**Comment by arkish** [comment] 2023-02-23 08:02
Output of `ls -la ssl/`

```total 32
drwxrwxr-x  2 css css 4096 Feb 23 14:57 .
drwxrwxr-x 21 css css 4096 Feb 23 15:04 ..
-rw-rw-r--  1 css css  506 Feb 23 14:57 ca_config.conf
-rw-rw-r--  1 css css 1269 Feb 23 14:57 ca.crt
-rw-------  1 css css 1704 Feb 23 14:57 ca.key
-rw-rw-r--  1 css css 1269 Feb 23 14:57 server.crt
-rw-rw-r--  1 css css 1029 Feb 23 14:57 server.csr
-rw-------  1 css css 1704 Feb 23 14:57 server.key
```

**Comment by dimakuv** [comment] 2023-02-23 08:08
Are you the `css` user on this system?

All files look good to me. Can you execute `openssl x509 -in ssl/server.crt -text -noout -certopt ext_parse` and show the output?

**Comment by arkish** [comment] 2023-02-27 03:07
yes. I'm the user. Output for `openssl x509 -in ssl/server.crt -text -noout -certopt ext_parse`:

`Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            52:70:6b:22:03:d8:35:ad:13:82:02:8c:e8:81:bc:8f:f1:64:ff:4f
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = XX, L = XXXXX, O = My Company, OU = Department, CN = localhost, emailAddress = me@example.com
        Validity
            Not Before: Feb 23 05:13:52 2023 GMT
            Not After : Feb 18 05:13:52 2024 GMT
        Subject: C = XX, L = XXXXX, O = My Company, OU = Department, CN = localhost, emailAddress = me@example.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:a9:8a:e2:c7:66:bf:90:62:8f:98:00:60:e5:af:
                    74:7c:7e:f4:bd:c3:3e:3e:fb:e2:f2:47:54:37:08:
                    42:6b:80:9a:d4:b9:92:52:8a:de:2f:a8:4a:cb:0d:
                    e2:01:83:6d:d4:2e:fb:39:25:c2:f5:e4:10:b0:39:
                    e1:ec:db:83:f1:2b:33:65:b8:6d:57:b8:90:d7:26:
                    cf:81:c5:9b:16:73:22:4f:19:5f:e6:db:c2:8a:1e:
                    5e:3d:8a:8f:35:29:24:d7:06:70:eb:04:ed:c0:76:
                    94:e9:e4:25:92:b7:cf:93:ec:28:42:f3:1f:8d:38:
                    a1:66:69:bb:ed:2e:5b:24:c0:a6:ed:ed:39:99:6e:
                    4c:5d:79:10:84:53:3b:91:d1:3f:46:1a:e1:1b:1b:
                    6b:a8:31:2b:1e:52:c1:f9:56:3e:c4:7f:95:6f:55:
                    c7:4e:cc:f2:ff:fa:f1:1d:91:ed:f0:0c:23:6e:e4:
                    b3:a4:b6:fd:57:6d:23:6d:76:2b:3a:e5:ce:cb:c7:
                    a4:bb:fb:49:89:54:4d:ad:85:b9:bc:cf:d6:7f:6a:
                    06:df:87:cd:32:66:14:30:47:af:5e:6b:09:9c:8d:
                    85:90:a3:44:a9:16:69:db:c3:c3:51:21:5a:54:b4:
                    0d:1b:3e:b5:6f:1a:62:b2:6f:be:45:0e:c3:aa:47:
                    cd:f7
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         4d:2a:4e:20:c4:dd:51:fc:b7:22:72:d0:1f:6b:04:57:97:17:
         dc:80:6a:57:3d:97:fe:f9:13:31:cd:d4:13:67:9f:62:ee:0d:
         d1:e6:86:0a:45:95:2f:10:f2:8c:ca:0f:34:0b:67:b4:c6:e3:
         a6:57:9c:14:42:3b:8c:38:7f:e1:23:78:1d:f9:1e:04:ae:fe:
         62:a4:a2:93:1e:5b:75:06:05:61:70:d7:64:5b:ad:10:b5:36:
         45:a2:8e:d5:0a:54:21:93:eb:95:f3:45:69:d3:ae:a6:8e:69:
         9a:b7:5f:21:26:4d:1d:51:84:0a:d5:b3:02:4f:74:6d:cf:67:
         c1:b6:ff:33:61:ed:9e:c4:da:12:9b:02:b9:67:94:11:e3:a3:
         65:15:03:e8:ec:5a:b1:17:e2:aa:3e:8d:69:ef:77:04:1c:d0:
         06:a2:f5:25:a7:7d:4b:9c:24:87:eb:8a:a1:1b:f4:22:7c:76:
         dc:af:a7:40:c0:31:3c:49:05:12:93:f7:85:8f:dd:d5:f5:84:
         ae:77:c8:45:23:cc:e1:5a:be:ac:6e:77:4a:f9:69:40:cf:f1:
         dd:cf:33:e5:b4:a2:1f:56:60:5a:1c:4d:f5:d1:13:5a:00:3f:
         67:be:99:9c:d3:d9:e2:a1:2a:e2:46:f3:77:1f:ff:83:88:38:
         1f:ee:ec:46
`

**Comment by arkish** [comment] 2023-02-27 03:10
Yes, I'm the user. Output for `openssl x509 -in ssl/server.crt -text -noout -certopt ext_parse`:

`Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            52:70:6b:22:03:d8:35:ad:13:82:02:8c:e8:81:bc:8f:f1:64:ff:4f
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = XX, L = XXXXX, O = My Company, OU = Department, CN = localhost, emailAddress = me@example.com
        Validity
            Not Before: Feb 23 05:13:52 2023 GMT
            Not After : Feb 18 05:13:52 2024 GMT
        Subject: C = XX, L = XXXXX, O = My Company, OU = Department, CN = localhost, emailAddress = me@example.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:a9:8a:e2:c7:66:bf:90:62:8f:98:00:60:e5:af:
                    74:7c:7e:f4:bd:c3:3e:3e:fb:e2:f2:47:54:37:08:
                    42:6b:80:9a:d4:b9:92:52:8a:de:2f:a8:4a:cb:0d:
                    e2:01:83:6d:d4:2e:fb:39:25:c2:f5:e4:10:b0:39:
                    e1:ec:db:83:f1:2b:33:65:b8:6d:57:b8:90:d7:26:
                    cf:81:c5:9b:16:73:22:4f:19:5f:e6:db:c2:8a:1e:
                    5e:3d:8a:8f:35:29:24:d7:06:70:eb:04:ed:c0:76:
                    94:e9:e4:25:92:b7:cf:93:ec:28:42:f3:1f:8d:38:
                    a1:66:69:bb:ed:2e:5b:24:c0:a6:ed:ed:39:99:6e:
                    4c:5d:79:10:84:53:3b:91:d1:3f:46:1a:e1:1b:1b:
                    6b:a8:31:2b:1e:52:c1:f9:56:3e:c4:7f:95:6f:55:
                    c7:4e:cc:f2:ff:fa:f1:1d:91:ed:f0:0c:23:6e:e4:
                    b3:a4:b6:fd:57:6d:23:6d:76:2b:3a:e5:ce:cb:c7:
                    a4:bb:fb:49:89:54:4d:ad:85:b9:bc:cf:d6:7f:6a:
                    06:df:87:cd:32:66:14:30:47:af:5e:6b:09:9c:8d:
                    85:90:a3:44:a9:16:69:db:c3:c3:51:21:5a:54:b4:
                    0d:1b:3e:b5:6f:1a:62:b2:6f:be:45:0e:c3:aa:47:
                    cd:f7
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         4d:2a:4e:20:c4:dd:51:fc:b7:22:72:d0:1f:6b:04:57:97:17:
         dc:80:6a:57:3d:97:fe:f9:13:31:cd:d4:13:67:9f:62:ee:0d:
         d1:e6:86:0a:45:95:2f:10:f2:8c:ca:0f:34:0b:67:b4:c6:e3:
         a6:57:9c:14:42:3b:8c:38:7f:e1:23:78:1d:f9:1e:04:ae:fe:
         62:a4:a2:93:1e:5b:75:06:05:61:70:d7:64:5b:ad:10:b5:36:
         45:a2:8e:d5:0a:54:21:93:eb:95:f3:45:69:d3:ae:a6:8e:69:
         9a:b7:5f:21:26:4d:1d:51:84:0a:d5:b3:02:4f:74:6d:cf:67:
         c1:b6:ff:33:61:ed:9e:c4:da:12:9b:02:b9:67:94:11:e3:a3:
         65:15:03:e8:ec:5a:b1:17:e2:aa:3e:8d:69:ef:77:04:1c:d0:
         06:a2:f5:25:a7:7d:4b:9c:24:87:eb:8a:a1:1b:f4:22:7c:76:
         dc:af:a7:40:c0:31:3c:49:05:12:93:f7:85:8f:dd:d5:f5:84:
         ae:77:c8:45:23:cc:e1:5a:be:ac:6e:77:4a:f9:69:40:cf:f1:
         dd:cf:33:e5:b4:a2:1f:56:60:5a:1c:4d:f5:d1:13:5a:00:3f:
         67:be:99:9c:d3:d9:e2:a1:2a:e2:46:f3:77:1f:ff:83:88:38:
         1f:ee:ec:46
`

**Comment by arkish** [comment] 2023-02-27 07:59
I had to copy the ssl folder in the parent directory using `cp -R gramine/CI-Examples/ra-tls-secret-prov/ssl ../` rather than the current directory

**Comment by dimakuv** [comment] 2023-02-28 08:40
@arkish Why did you reopen this issue? Isn't it a duplicate of #1202? If so, then let's keep our discussions in only one issue. And I suggest it to be #1202 rather than this one.

**Closed** 2023-02-28 08:43 UTC
