### ISSUE TITLE
Help needed diagnosing 100% CPU usage during enclave startup

### ISSUE THREAD

**Issue by jtdaugherty** [gramineproject/gramine#998] opened 2022-10-20 17:38 UTC
### Description of the problem

When starting my enclave, the loader seems to reach a point where it gets to 100% CPU usage (for 16 hours in one test before I killed it). I can't tell whether the loader itself is getting stuck, or whether it's actually running the enclave program itself and getting stuck there.

### Steps to reproduce

I can't say how to reproduce this; I don't know what conditions cause it, although I can say what I'm running and what I've tried: the enclave binary is 51 MB, the enclave size in the manifest is set to 2 GB (the program I'm trying to run should only need 200 MB of residency at most). I'm running Gramine `1.3.1-1~ubuntu0.18.04` on Ubuntu 20.04 using the `focal` sources.list entry.

### Expected results

Naturally, what I'm hoping to see is that the enclave program runs (as evidenced by just seeing the console output from it that I expect to see).

### Actual results

The loader gets to this point (with log level `debug`) and then we get into 100% CPU usage on one core for as long as I let it run:
```
debug: LibOS loaded at 0x7efd5000, ready to initialize
debug: mounting "file:." (chroot) under /
debug: mounting "proc" (pseudo) under /proc
debug: mounting "dev" (pseudo) under /dev
debug: mounting "dev:tty" (chroot) under /dev/tty
debug: mounting "sys" (pseudo) under /sys
debug: Creating pipe: pipe.srv:fe7aaec55f2bbe05a3531ae7910cd1a732c339f635b355bd337c3de8fdb3f867
[P1:T1:] error: Detected deprecated syntax: 'fs.mount'. Consider converting to the new array syntax: 'fs.mounts = [{ type = "chroot", uri = "...", path = "..." }]'.
[P1:T1:] debug: mounting "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc" (chroot) under /lib
[P1:T1:] debug: mounting "file:/usr/lib/x86_64-linux-gnu" (chroot) under /lib2
[P1:T1:interpreter-service] debug: Creating pipe: pipe.srv:f4e35610474a04a9194ba462624cf19c317155ee368fd8d903aec1ee7d8cecf4
[P1:T1:interpreter-service] debug: Allocated stack at 0x48e40000 (size = 0x40000)
[P1:T1:interpreter-service] debug: loading "file:./interpreter-service"
[P1:T1:interpreter-service] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P1:T1:interpreter-service] debug: loading "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/ld-linux-x86-64.so.2"
[P1:T1:interpreter-service] debug: Creating pipe: pipe.srv:1
[P1:T1:interpreter-service] debug: Creating pipe: pipe.srv:8b165d0b493bbebaf2df88f5690dfb38582cc2af4cd6cd3cf609dea2ec8eedb1
[P1:T1:interpreter-service] debug: LibOS initialized
[P1:libos] debug: IPC worker started
[P1:T1:interpreter-service] debug: glibc register library /lib2/libprotobuf-c.so.1 loaded at 0x48df9000
[P1:T1:interpreter-service] debug: glibc register library /lib/libpthread.so.0 loaded at 0x48df4000
[P1:T1:interpreter-service] debug: glibc register library /lib2/libz.so.1 loaded at 0x48dd8000
[P1:T1:interpreter-service] debug: glibc register library /lib/librt.so.1 loaded at 0x48dd3000
[P1:T1:interpreter-service] debug: glibc register library /lib/libutil.so.1 loaded at 0x48dce000
[P1:T1:interpreter-service] debug: glibc register library /lib/libdl.so.2 loaded at 0x48dc9000
[P1:T1:interpreter-service] debug: glibc register library /lib2/libgmp.so.10 loaded at 0x48d43000
[P1:T1:interpreter-service] debug: glibc register library /lib/libc.so.6 loaded at 0x48b4f000
[P1:T1:interpreter-service] debug: glibc register library /lib/libm.so.6 loaded at 0x48a71000
[P1:T1:interpreter-service] warning: Unsupported system call rseq
[P1:T1:interpreter-service] warning: Per-process and per-thread CPU-time clocks are not supported in clock_gettime(); they are replaced with system-wide real-time clock.
```
With the log level set to `all`, I see these messages repeating indefinitely:
```
[P1:T1:interpreter-service] trace: ---- clock_gettime(1, 0x55a809a0) = 0x0
[P1:T1:interpreter-service] trace: ---- pselect6(3, 0x55a80a10, 0x55a80a90, 0, 0, 0) ...
[P1:T1:interpreter-service] trace: ---- return from pselect6(...) = 0x0
```

### Gramine commit hash

1.3.1-1~ubuntu0.18.04

**Comment by jtdaugherty** [comment] 2022-10-20 17:45
A related question: if the program in my process table is still listed as `loader`, does that mean the enclave program has not yet started? I ask since my manifest specifies `loader.argv0_override` and I don't know at what point in the process that override takes effect, but I'm wondering if that's one way to tell what stage the loader is at.

**Comment by boryspoplawski** [comment] 2022-10-20 17:59
> With the log level set to all, I see these messages repeating indefinitely:

Hard to say, but that might be some Gramine bug. Could you share some logs from before these looping lines? (you can log to file using `loader.log_file = "filename"` if needed)

> A related question: if the program in my process table is still listed as loader, does that mean the enclave program has not yet started? I ask since my manifest specifies loader.argv0_override and I don't know at what point in the process that override takes effect, but I'm wondering if that's one way to tell what stage the loader is at.

That's normal, this override is internal to Gramine, i.e. processes running inside Gramine will see it.

**Comment by jtdaugherty** [comment] 2022-10-20 18:03
> Could you share some logs from before these looping lines?

Here you go.
[shortlog.txt](https://github.com/gramineproject/gramine/files/9832767/shortlog.txt)

**Comment by boryspoplawski** [comment] 2022-10-20 18:17
So, it looks like Gramine `pselect6` is bugged and returns immediately even though timeout is specified as NULL. But other than 100% usage (effectively a busy loop happening) the program should work, it seems to wait for input on some fds (stdin most likely).

**Comment by jtdaugherty** [comment] 2022-10-20 18:20
> But other than 100% usage (effectively a busy loop happening) the program should work

Are you thinking that the `pselect6` bug is the cause of the busy loop?

> it seems to wait for input on some fds (stdin most likely).

Can you point me to the `shortlog.txt` line that gives you this clue?

**Comment by boryspoplawski** [comment] 2022-10-20 18:23
> Are you thinking that the pselect6 bug is the cause of the busy loop?

That's for sure - your app requests it to sleep until some fd is ready, but it returns immediately returning `0` - no fds ready. So app repeats that, ad infinitum.

> Can you point me to the shortlog.txt line that gives you this clue?

It's just that the app did nothing important, more precisely, it did not open any fds before issuing `pselect6, which means only available fds are `0`, `1` and `2`.
The log is essentially trace of all syscalls issued by the app (plus some internal Gramine logs, but they are rather rare)

**Comment by boryspoplawski** [comment] 2022-10-20 18:32
Quite possibly the next release, but it will be a couple (~3) of months.

**Comment by jtdaugherty** [comment] 2022-10-20 18:33
Do you have any hints as to what to look for in fixing this? If so, I could attempt a local fix just to be able to make progress on the project that I'm working on.

**Comment by jtdaugherty** [comment] 2022-10-20 18:38
> Gramine pselect6 is bugged and returns immediately even though timeout is specified as NULL

This is probably enough for me to investigate, in any case.

**Comment by jtdaugherty** [comment] 2022-10-20 18:48
For what it's worth, Gramine's `libos_syscall_pselect6` just passes `NULL` as the timeout to `select()` if no timeout is given to `pselect6`. That, in turn, gets passed on to `_libos_syscall_poll`, then `PalStreamsWaitEvents`, and eventually `ocall_poll`.
```c
    if (tsp) {
        struct __kernel_timeval tsv;
        tsv.tv_sec  = tsp->tv_sec;
        tsv.tv_usec = tsp->tv_nsec / 1000;
        return libos_syscall_select(nfds, readfds, writefds, errorfds, &tsv);
    }

    return libos_syscall_select(nfds, readfds, writefds, errorfds, NULL);
```

**Comment by boryspoplawski** [comment] 2022-10-20 19:16
We have plans for rewriting `poll` and `select` (`epoll` was already rewritten). Where the bug lies exactly I cannot tell without looking more at the code (but there are many many bugs there)

**Comment by dimakuv** [comment] 2022-10-21 07:57
Yes, I agree with @boryspoplawski. A quick look at the code leads me to `_libos_syscall_poll()` which definitely has some bugs inside. Since we have only `0`, `1` and `2` FDs in this example (stdin, stdout, stderr), and in Gramine they are marked as `TYPE_DEV` handles, I think the problem lies somewhere around these lines: https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/libos/src/sys/libos_poll.c#L99-L123

In general, the file `libos_poll.c` should be seriously tested and re-written... Interestingly, we never encountered problems with select/poll before, probably because all modern applications prefer `epoll`.

**Comment by boryspoplawski** [comment] 2022-11-30 01:48
The problem is that `poll` is not implemented for fds `0`, `1` and `2` (they are all `/dev/tty` opened in Gramine). https://github.com/gramineproject/gramine/pull/1067 fixes some bugs around it, but there are more fixes needed around these "devices" in Gramine

**Comment by dimakuv** [comment] 2022-12-01 08:49
> The problem is that `poll` is not implemented for fds `0`, `1` and `2` (they are all `/dev/tty` opened in Gramine). 

@boryspoplawski I don't think it's true? FDs 0, 1 and 2 are served by the `chroot` type of FS, which has this `poll()` callback:
- https://github.com/gramineproject/gramine/blob/da990909010a5989dc89c63f4c7a22d78fb3f5c6/libos/src/fs/chroot/fs.c#L508?plain=1
- https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/libos/src/fs/libos_fs_util.c#L119?plain=1

And it looks like for these FDs (which should be `S_IFCHR` type) the callback returns `-EAGAIN`: https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/libos/src/fs/libos_fs_util.c#L135

And in the poll syscall emulation, we don't even check for error codes: https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/libos/src/sys/libos_poll.c#L112-L114

**Comment by boryspoplawski** [comment] 2022-12-01 22:31
Returning `-EAGAIN` is what I call "not implemented".

**Comment by dimakuv** [comment] 2023-01-06 09:48
@jtdaugherty We just merged #1067, maybe you could try the newest `master` branch of Gramine and check again? Hopefully your problem goes away now.

**Comment by jtdaugherty** [comment] 2023-01-09 16:54
@dimakuv I'm not in a position to try a source build at the moment. My project needs to use the `gramine-oot` build that is provided for Ubuntu; once this change is released, I could try it then!

**Comment by dimakuv** [comment] 2023-01-10 09:46
> My project needs to use the gramine-oot build that is provided for Ubuntu; once this change is released, I could try it then!

I have bad news for you... We are abandoning Ubuntu packages for `gramine-oot`. It was decided that the OOT deployments are not worth the maintenance cost, and Gramine will *not* supply OOT packages anymore.

The only way to use OOT in Gramine in the near future will be to build from source.

**Comment by jtdaugherty** [comment] 2023-01-16 17:29
Okay, thanks, @dimakuv. It's been a while since I used Gramine on my project, but can you help me understand what "OOT" means? I remember using the `gramine-oot` package on Ubuntu when I set up my project, but I don't recall why (perhaps it was the only one available, so that's what I installed). I seem to remember this standing for "out of tree," but I don't know what that means or what its opposite would mean, either.

**Comment by jtdaugherty** [comment] 2023-01-16 17:31
I looked at the package description again and I see that the OOT package says "using SGX SDK kernel driver" rather than the DCAP driver (which I didn't want to use, or couldn't use, I don't recall). How is the `gramine-oot` package different than just `gramine`? Its description doesn't seem to say much about how it differs.

**Comment by jtdaugherty** [comment] 2023-01-16 22:49
@dimakuv I got some time to try out my project with the latest build of `master` that includes the fix mentioned above, and my program no longer encounters the 100% CPU problem I reported in this ticket. Thank you!

**Comment by mkow** [comment] 2023-01-16 23:24
Good to hear :) I assume then that we can close the issue.

**Closed by mkow** 2023-01-16 23:24 UTC
Labels: bug

**Comment by dimakuv** [comment] 2023-01-17 09:26
> How is the `gramine-oot` package different than just `gramine`?

@jtdaugherty Your understanding is correct:

- `gramine-oot` package is built against the out-of-tree legacy Intel SGX driver (https://github.com/intel/linux-sgx-driver)
    - this is the only driver that can be used on non-[FLC](https://gramine.readthedocs.io/en/latest/sgx-intro.html#term-flc) SGX machines (very old ones).
    - this driver is completely deprecated since Linux 5.11, where the new in-tree Intel SGX driver was merged.

- `gramine` package is built against the new in-tree Intel SGX driver.
    - this driver is backed into Linux starting from v5.11.
    - this driver also exists in the out-of-tree implementation (for e.g. Linux 5.4), also called "DCAP SGX driver".

You can also read a bit here: https://gramine.readthedocs.io/en/latest/sgx-intro.html#linux-kernel-drivers

I hope this clarifies the difference between packages, and why Gramine will only ship `gramine` in the future.
