### ISSUE TITLE
Mounting failed on helloworld example

### ISSUE THREAD

**Issue by oubotong** [gramineproject/gramine#236] opened 2021-11-22 02:35 UTC
## Description of the problem

I tried to build the Gramine with -Ddirect=enabled only in the debug mode.  Then I build the examples in the `Pal/regression`  by get into the folders and run `make`.

Then I run the command `gramine-direct helloworld` for simple testing and an errorscome out.

## Steps to reproduce

Build the Gramine by `meson setup build/ --buildtype=debug -Ddirect=enabled -Dsgx=disabled`
Build the examples in `Pal/regression` by `make -j4`
Run the test example by `gramine-direct helloworld`

## Expected results
Output `helloworld` string
## Actual results
```
[P1:T1:] error: Mounting file:/usr/local/lib/x86_64-linux-gnu/gramine/tests/libos/regression/helloworld on helloworld (type=chroot) failed (2)
[P1:T1:] error: Error during shim_init() in init_mount (-2)
```

**Comment by oubotong** [comment] 2021-11-22 02:50
The name of the helloworld example is `HelloWorld`

**Comment by oubotong** [comment] 2021-11-22 04:37
The HelloWorld example is for the latest branch, mine fork is the `borys/aex_ocalls`. I followed the build instructions in this version of building the helloworld example in `LibOS/shim/test/regression`. The same error happens.

**Comment by dimakuv** [comment] 2021-11-22 07:33
@boryspoplawski Could you rebase your branch `borys/aex_ocalls` to the latest master, so @oubotong can use our build instructions?

@oubotong For the context: we had a bug in our build instructions. The bug was fixed recently, but the branch `borys/aex_ocalls` is still "old" and doesn't contain that bug fix. Borys will fix it soon-ish.

**Comment by oubotong** [comment] 2021-11-22 15:48
Thanks for the information. I will wait for the bug fix then. I will also look into the latest branch.

**Comment by boryspoplawski** [comment] 2021-11-23 05:34
@oubotong Why are you using this branch instead of master? It contains a very specific, experimental code which only runs on SGX PAL, which you do not use (judging from your build commands).

FWIW: I did a rebase.

@dimakuv What bug? We don't have `helloworld` in Pal/regression on master, so not sure how a rebase is supposed to help.

**Comment by dimakuv** [comment] 2021-11-23 07:12
@boryspoplawski I think he is collecting perf numbers of your branch? That's what I thought. But maybe I am mistaken; @oubotong Why are you using exactly the `borys/aex_ocalls` branch instead of `master`? What are you trying to achieve?

@dimakuv I'm talking about that bug: https://github.com/gramineproject/gramine/pull/188. It is clear that @oubotong made a mistake/typo when he mentioned `Pal/regression` because it is clear from the logs and his other sentences that he is actually checking `LibOS/shim/regression` tests (we asked users to run `helloworld` there previously).

**Comment by boryspoplawski** [comment] 2021-11-23 07:17
@dimakuv so running that example from LibOS/regression should work before rebase, which is what @oubotong did, I believe.

**Comment by dimakuv** [comment] 2021-11-23 07:23
@boryspoplawski There was a week or two when running `helloworld` from LibOS/regression was broken. (The user had to add `-Dtests=enabled` during meson setup, which we did *not* specify in the documentation.) So I just assumed that you created your `aex_ocalls` branch around that time, where we had that bug.

**Comment by boryspoplawski** [comment] 2021-11-23 07:28
@dimakuv Ah, you are right, that's possible

**Comment by dimakuv** [comment] 2021-11-25 07:30
@oubotong What is the status now? Have you tried the new version of the `borys/aex_ocalls` branch now? It should definitely work now. I'm currently closing this issue, but if you still have problems, feel free to re-open the issue.

**Closed by dimakuv** 2021-11-25 07:30 UTC
