### ISSUE TITLE
Build Gramine failed in subproject glibc

### ISSUE THREAD

**Issue by yanzhaoINT** [gramineproject/gramine#524] opened 2022-04-12 16:22 UTC
## Description of the problem

I followed the building steps in this [documentation](https://gramine.readthedocs.io/en/latest/devel/building.html).
Steps were done to the final building step:

```
sudo ninja -C build/ install
```

There was an error related the glibc subproject. The log was as below:

```
gcc -Wl,-rpath-link=/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/math:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/dlfcn:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nss:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nis:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/rt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/resolv:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/mathvec:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/crypt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nptl -pie -Wl,-O1 -nostdlib -nostartfiles -o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/echo-container    -Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/Scrt1.o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crti.o `gcc  --print-file-name=crtbeginS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/echo-container.o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/libsupport_nonshared.a  -Wl,-dynamic-linker=/usr/local/lib/ld-linux-x86-64.so.2  /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc.so.6 /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc_nonshared.a -Wl,--as-needed /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf/ld.so -Wl,--no-as-needed -lgcc  `gcc  --print-file-name=crtendS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crtn.o
gcc -Wl,-rpath-link=/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/math:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/dlfcn:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nss:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nis:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/rt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/resolv:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/mathvec:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/crypt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nptl -pie -Wl,-O1 -nostdlib -nostartfiles -o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/true-container    -Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/Scrt1.o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crti.o `gcc  --print-file-name=crtbeginS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/true-container.o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/libsupport_nonshared.a  -Wl,-dynamic-linker=/usr/local/lib/ld-linux-x86-64.so.2  /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc.so.6 /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc_nonshared.a -Wl,--as-needed /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf/ld.so -Wl,--no-as-needed -lgcc  `gcc  --print-file-name=crtendS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crtn.o
gcc -Wl,-rpath-link=/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/math:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/dlfcn:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nss:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nis:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/rt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/resolv:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/mathvec:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/crypt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nptl -pie -Wl,-O1 -nostdlib -nostartfiles -o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/shell-container    -Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/Scrt1.o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crti.o `gcc  --print-file-name=crtbeginS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/shell-container.o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/libsupport_nonshared.a  -Wl,-dynamic-linker=/usr/local/lib/ld-linux-x86-64.so.2  /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc.so.6 /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc_nonshared.a -Wl,--as-needed /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf/ld.so -Wl,--no-as-needed -lgcc  `gcc  --print-file-name=crtendS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crtn.o
gcc -Wl,-rpath-link=/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/math:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/dlfcn:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nss:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nis:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/rt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/resolv:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/mathvec:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/crypt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nptl -pie -Wl,-O1 -nostdlib -nostartfiles -o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/test-container    -Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/Scrt1.o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crti.o `gcc  --print-file-name=crtbeginS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/test-container.o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/libsupport_nonshared.a -Wl,-dynamic-linker=/usr/local/lib/ld-linux-x86-64.so.2  /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc.so.6 /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc_nonshared.a -Wl,--as-needed /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf/ld.so -Wl,--no-as-needed -lgcc  `gcc  --print-file-name=crtendS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crtn.o
gcc -Wl,-rpath-link=/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/math:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/dlfcn:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nss:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nis:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/rt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/resolv:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/mathvec:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/crypt:/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/nptl -pie -Wl,-O1 -nostdlib -nostartfiles -o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/links-dso-program    -Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/Scrt1.o /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crti.o `gcc  --print-file-name=crtbeginS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/links-dso-program.o -lstdc++ -lgcc -lgcc_s  -Wl,-dynamic-linker=/usr/local/lib/ld-linux-x86-64.so.2  /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc.so.6 /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/libc_nonshared.a -Wl,--as-needed /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/elf/ld.so -Wl,--no-as-needed -lgcc  `gcc  --print-file-name=crtendS.o` /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/csu/crtn.o
/usr/local/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libgcc_s.so.1: undefined reference to `_dl_find_object@GLIBC_2.35'
collect2: error: ld returned 1 exit status
make[2]: *** [../Rules:222: /home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/build/support/links-dso-program] Error 1
make[2]: Leaving directory '/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/support'
make[1]: *** [Makefile:478: support/others] Error 2
make[1]: Leaving directory '/home/int_license/sgx/gramine/build/subprojects/glibc-2.34-1/crt1.o.p'
make: *** [Makefile:9: all] Error 2
```

## Expected results
Gramine should be built and installed properly.
## Actual results
Could not build Gramine 

 ## Additional information
Environment:
Ubuntu 22.04
Kernel: 5.15.0-25-generic
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Ubuntu GLIBC 2.35-0ubuntu3
CPU: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
MemTotal:       32612248 kB

```bash
$ lsmod | grep sgx
isgx                   57344  0
```

```bash
$ ls /dev/*sgx*
/dev/isgx  /dev/sgx_provision  /dev/sgx_vepc

/dev/sgx:
provision
```

```
meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled -Dsgx_driver=oot -Dsgx_driver_include_path=/var/inplay/sgx/sgx-package/linux-sgx-driver/
The Meson build system
Version: 0.61.2
Source dir: /home/int_license/sgx/gramine
Build dir: /home/int_license/sgx/gramine/build
Build type: native build
Project name: gramine
Project version: 1.1post-UNRELEASED
C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C linker for the host machine: cc ld.bfd 2.36.1
C++ compiler for the host machine: c++ (gcc 11.2.0 "c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C++ linker for the host machine: c++ ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program check-no-reloc.sh found: YES (/home/int_license/sgx/gramine/Scripts/check-no-reloc.sh)
Program gen-pal-map.py found: YES (/home/int_license/sgx/gramine/Scripts/gen-pal-map.py)
Program get-python-platlib.py found: YES (/home/int_license/sgx/gramine/Scripts/get-python-platlib.py)
Program meson-clang-format.sh found: YES (/home/int_license/sgx/gramine/Scripts/meson-clang-format.sh)
Program objcopy found: YES (/usr/local/bin/objcopy)
meson.build:49: WARNING: Project targeting '>=0.55' but tried to use feature deprecated since '0.48.0': python3 module.
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Compiler for C supports arguments -Wtrampolines: YES 
Compiler for C supports arguments -Wnull-dereference: YES 
meson.build:72: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
meson.build:72: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Has header "/var/inplay/sgx/sgx-package/linux-sgx-driver/sgx_user.h" : YES 
Program nm found: YES (/usr/bin/nm)
Compiler for C supports arguments -fstack-protector-strong -mstack-protector-guard=tls -mstack-protector-guard-reg=%gs -mstack-protector-guard-offset=8: YES 

Executing subproject tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5 

tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5| Project name: tomlc99
tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5| Project version: undefined
tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5| C linker for the host machine: cc ld.bfd 2.36.1
tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5| Program patch found: YES (/usr/bin/patch)
tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5| Build targets in project: 2
tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5| Subproject tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5 finished.


Executing subproject uthash-2.1.0 

uthash-2.1.0| Project name: uthash
uthash-2.1.0| Project version: undefined
uthash-2.1.0| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
uthash-2.1.0| C linker for the host machine: cc ld.bfd 2.36.1
uthash-2.1.0| Program patch found: YES (/usr/bin/patch)
uthash-2.1.0| Build targets in project: 3
uthash-2.1.0| Subproject uthash-2.1.0 finished.


Executing subproject mbedtls-mbedtls-2.26.0-1 

mbedtls-mbedtls-2.26.0-1| Project name: mbedtls
mbedtls-mbedtls-2.26.0-1| Project version: undefined
mbedtls-mbedtls-2.26.0-1| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
mbedtls-mbedtls-2.26.0-1| C linker for the host machine: cc ld.bfd 2.36.1
mbedtls-mbedtls-2.26.0-1| Program compile-gramine.sh found: YES (/bin/sh /home/int_license/sgx/gramine/subprojects/mbedtls-mbedtls-2.26.0-1/compile-gramine.sh)
mbedtls-mbedtls-2.26.0-1| Program compile-pal.sh found: YES (/home/int_license/sgx/gramine/subprojects/mbedtls-mbedtls-2.26.0-1/compile-pal.sh)
mbedtls-mbedtls-2.26.0-1| Build targets in project: 5
mbedtls-mbedtls-2.26.0-1| Subproject mbedtls-mbedtls-2.26.0-1 finished.

Program protoc-c found: YES (/usr/bin/protoc-c)
Run-time dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libcurl found: YES 7.81.0
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency cjson found: NO (tried pkgconfig and cmake)
Library cjson found: NO

Executing subproject cJSON-1.7.12 

cJSON-1.7.12| Project name: cJSON
cJSON-1.7.12| Project version: undefined
cJSON-1.7.12| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
cJSON-1.7.12| C linker for the host machine: cc ld.bfd 2.36.1
cJSON-1.7.12| Build targets in project: 5
cJSON-1.7.12| Subproject cJSON-1.7.12 finished.

Run-time dependency libprotobuf-c found: YES 1.3.3
Configuring gsgx.h using configuration
Compiler for C supports arguments -Wno-null-dereference: YES 
Compiler for C supports arguments -Wno-gnu-alignof-expression: NO 
Compiler for C supports arguments -Wno-address-of-packed-member: YES 
Configuring __init__.py using configuration
Configuring gramine-direct using configuration
Configuring gramine-sgx using configuration

Executing subproject glibc-2.34-1 

glibc-2.34-1| Project name: glibc
glibc-2.34-1| Project version: 2.34
glibc-2.34-1| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
glibc-2.34-1| C linker for the host machine: cc ld.bfd 2.36.1
glibc-2.34-1| Program compile.sh found: YES (/bin/sh /home/int_license/sgx/gramine/subprojects/glibc-2.34-1/compile.sh)
glibc-2.34-1| Build targets in project: 35
glibc-2.34-1| Subproject glibc-2.34-1 finished.


Executing subproject musl-1.2.2 

musl-1.2.2| Project name: musl
musl-1.2.2| Project version: 1.2.2
musl-1.2.2| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
musl-1.2.2| C linker for the host machine: cc ld.bfd 2.36.1
musl-1.2.2| Program compile.sh found: YES (/bin/sh /home/int_license/sgx/gramine/subprojects/musl-1.2.2/compile.sh)
musl-1.2.2| Build targets in project: 36
musl-1.2.2| Subproject musl-1.2.2 finished.

Build targets in project: 37
WARNING: Deprecated features used:
 * 0.48.0: {'python3 module'}

gramine 1.1post-UNRELEASED

  Subprojects
    cJSON-1.7.12                                    : YES
    glibc-2.34-1                                    : YES
    mbedtls-mbedtls-2.26.0-1                        : YES
    musl-1.2.2                                      : YES
    tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5: YES
    uthash-2.1.0                                    : YES

  User defined options
    buildtype                                       : release
    direct                                          : enabled
    sgx                                             : enabled
    sgx_driver                                      : oot
    sgx_driver_include_path                         : /var/inplay/sgx/sgx-package/linux-sgx-driver/

Found ninja-1.10.1 at /usr/bin/ninja

```

## Gramine commit hash
3ec7e577b1b6ff8f942f5b3f068254e45a6c0e63

**Comment by yanzhaoINT** [comment] 2022-04-14 14:57
I tried to apply that patch but didn't help. Still get the same issue during building process.

**Comment by dimakuv** [comment] 2022-04-14 15:00
I tested it just now (for unrelated reasons), and it works for me.

**Comment by dimakuv** [comment] 2022-04-14 15:01
@yanzhaoINT You may want to remove the whole Gramine dir, git-clone it again, apply the patch from Borys, and only then build from scratch.

The problem is: you may still have the old incorrect build of Glibc hidden in `build/` or `subpackages/` directories, and so the "bad" Glibc is not re-built.

**Comment by mkow** [comment] 2022-04-28 18:23
No reply from the reporter for quite some time, closing.

**Closed by mkow** 2022-04-28 18:23 UTC
