### ISSUE TITLE
Pal testcase "Memory" failing with gramine-direct

### ISSUE THREAD

**Issue by aniket-intelx** [gramineproject/gramine#104] opened 2021-09-30 07:24 UTC
## Description of the problem
The testcase "Memory" in Pal regression test suite is failing consistently with `gramine-direct`. We have observed this failure on 2/7 systems in CI (Ubuntu 20.04 (kernel: 5.12.0-051200-generic) and RHEL (kernel: 5.13.0) machines).
Failure is observed from commit `b4bfd028f85af83bbb1e27aa6037808e13965833` ([Pal/Linux] Disable host-level ASLR in PAL Linux) and it passes for commits prior to this.
Please note: GSGX works for this test.
## Steps to reproduce
Run below mentioned command:
gramine-direct Memory

## Expected results
Memory Allocation OK
(int *) 0x7f3639353000 = 0
Memory Allocation Protection (RW) OK
Memory Fault 1
Memory Protection (R) OK
Memory Fault 2
Memory Deallocation OK
Memory Allocation with Address OK
Total Memory: 16336474112
Get Memory Available Quota OK
## Actual results
Memory Allocation OK    
(int *) 0x7fffeffce000 = 0
Memory Allocation Protection (RW) OK
Memory Fault 1
Memory Protection (R) OK
Memory Fault 2
Memory Deallocation OK
Total Memory: 16336474112
Get Memory Available Quota OK

The test is missing the message, "Memory Allocation with Address OK" in output and thus asserting.

**Comment by dimakuv** [comment] 2021-09-30 08:18
@aniket-intelx Are you using Docker for your CI? Please check this: https://github.com/gramineproject/graphene/pull/2597#pullrequestreview-718770270

If you're using Docker, try adding this option to your `docker run` command as a quick test: `--security-opt seccomp=unconfined`

**Comment by aniket-intelx** [comment] 2021-09-30 08:31
The failure is observed on host systems.

**Comment by dimakuv** [comment] 2021-09-30 09:58
> We have observed this failure on 2/7 systems in CI

Any more specifics? This problem cannot be reproduced on our Ubuntus. Is this failure specific to CentOS/RHEL?

**Comment by boryspoplawski** [comment] 2021-09-30 10:46
> We have observed this failure on 2/7 systems in CI (Ubuntu 20.04 (kernel: 5.12.0-051200-generic) and RHEL (kernel: 5.13.0) machines).

@dimakuv so I guess it also triggered for Ubuntu 20.04

**Comment by aniket-intelx** [comment] 2021-09-30 10:52
We have observed this failure on Ubuntu 20.04 with 5.12 kernel and RHEL with 5.13 kernel machines on baremetal. Both of these systems are client.
We tried increasing the pal_internal_memsize from default 128M to 512M but the test still fails.

The `ret = DkVirtualMemoryAlloc(&mem4, UNIT, 0, PAL_PROT_READ | PAL_PROT_WRITE);` value is printed below:
Memory Allocation OK
(int *) 0x7fffe3fce000 = 0
Memory Allocation Protection (RW) OK
Memory Fault 1
Memory Protection (R) OK
Memory Fault 2
Memory Deallocation OK
Ret 2 0
Ret -16
Total Memory: 16336474112
Get Memory Available Quota OK

The value received is -16.

Please let me know if you need access to system.

**Comment by dimakuv** [comment] 2021-09-30 11:31
@aniket-intelx Could you run the failing test with `loader.log_level = "all"` and paste the output log?

**Comment by aniket-intelx** [comment] 2021-09-30 12:39
The output log remains the same after setting the `loader.log_level = "all"`.

**Comment by jinengandhi-intel** [comment] 2021-10-07 05:56
If you don't have a machine with such a configuration, then contact @aniket-intelx, we will try to get you a machine.

**Comment by aniket-intelx** [comment] 2021-10-07 08:44
I have shared the credentials of machine with @jkr0103

**Comment by dimakuv** [comment] 2021-11-25 07:53
@aniket-intelx @jkr0103 Any update on this issue? For now, I'll add the labels Bug and P1.

**Comment by jinengandhi-intel** [comment] 2021-11-25 08:17
We haven't heard back from Jitender, I guess he was on leave so.

**Comment by jkr0103** [comment] 2021-12-13 10:24
Issue is not seen on latest gramine (commit 144e4f66a9d76fc0c85eb53acf1425bbefa3bcb3) on the same ubuntu 20.04 machine, @aniket-intelx have shared and where issue was seen around two months before.

**Comment by dimakuv** [comment] 2021-12-13 10:39
Looks like we can close this issue. @aniket-intelx If you still observe it on some machines, feel free to reopen the issue.

**Closed by dimakuv** 2021-12-13 10:39 UTC
Labels: bug, P: 1
