### ISSUE TITLE
Issue in creating Protected file

### ISSUE THREAD

**Issue by sivashax** [gramineproject/gramine#641] opened 2022-06-08 10:02 UTC
## Description of the problem
With Gramine 1.2 TAG seeing issue with Protected file creation. When the protected file / plain txt file is already available, opening the file again in *write* mode is failing. FYI, this was working in previous version of Gramine.

## Steps to reproduce
Use attached sample program. Place it in gramine source directory and compile. Create "prot_dir" in /tmp for creating protected file.
Run as below.
gramine-sgx protect_file /tmp/prot_dir/sample.txt -> Protected file would be created.

Run the same command again.
sample.txt should be created again in /tmp/prot_dir. However, its failing in this release.

## Expected results

Able to open the protected file / plain text file if already available for creating as protected file.

## Actual results

File open is failing, incase if file is already available in protected file path.

## Gramine commit hash
commit 132ebc14fd339232a95538b920efa85e6119693c

**Comment by sivashax** [comment] 2022-06-08 10:03
[protect_file.tar.gz](https://github.com/gramineproject/gramine/files/8860542/protect_file.tar.gz)

**Comment by dimakuv** [comment] 2022-06-09 06:56
@mkow Could we assign someone to it?

**Comment by oshogbo** [comment] 2022-06-09 10:12
I can take a look.

**Comment by oshogbo** [comment] 2022-06-09 14:51
It seems that the issue is the file truncation functionality in protected files.
```
[P1:T1:protect_file] debug: ipf_open: handle: 0, path: '/tmp/prot_dir/sample.txt', real size: 4096, mode: 0x3
[P1:T1:protect_file] debug: ipf_init_existing_file: data size 37
[P1:T1:protect_file] debug: ipf_open: OK (data size 37)
[P1:T1:protect_file] warning: encrypted_file_set_size: pf_set_size failed: Functionality not implemented
```
The `fopen(..., "w")` from GLIBC uses `openat(2)` with `O_TRUNC` flag. This ends up calling the `pf_set_size` function with size equals to 0. 
```
// TODO: file truncation
pf_status_t pf_set_size(pf_context_t* pf, uint64_t size) {
```

I will add at least 0 size truncation ASAP.

**Comment by oshogbo** [comment] 2022-06-09 15:38
> FYI, this was working in previous version of Gramine.

[sivashax](https://github.com/sivashax) Could I ask you for a code that was working for you on 1.1? Probably you have a different manifest file. The example you sent works on 1.2 (and I was able to reproduce the bug) but doesn't work on 1.1 at all.

**Comment by sivashax** [comment] 2022-06-10 09:05
Yes, since there is change in manifest syntax w.r.t Protected files, the earlier attached manifest file doesnt work with Gramine 1.1 TAG. Attached the manifest file for Gramine 1.1 TAG.
[protect_file.manifest.template_gramine1.1.zip](https://github.com/gramineproject/gramine/files/8877480/protect_file.manifest.template_gramine1.1.zip)

**Comment by mkow** [comment] 2022-06-15 14:03
@sivashax: Could you check if  https://github.com/gramineproject/gramine/pull/651 fixes your problem?

**Comment by sivashax** [comment] 2022-06-17 12:03
@ mkow, yes this fixes our problem. Thanks for support. Please let me know, when this PR would be integrated into Master branch.

**Comment by mkow** [comment] 2022-06-23 14:09
@sivashax: We just merged https://github.com/gramineproject/gramine/pull/651, I'm closing this issue.

**Closed by mkow** 2022-06-23 14:09 UTC
