### ISSUE TITLE
[LibOS] experimental flock significantly increases file size

### ISSUE THREAD

**Issue by fnerdman** [gramineproject/gramine#1811] opened 2024-03-14 09:43 UTC
### Description of the problem

Running go-ethereum in Gramine with experimental flock support we experience an increase of file size (300-1000%) compared to not setting the flock for the database folders.

### Gramine commit hash

v1.6

**Comment by lead4good** [comment] 2024-03-21 15:42
After doing some more digging, this seems to be related to a regression in gramine's tmpfs implementation rather than flock. The increased file size is not observable when running gramine 1.5, whereas gramine +1.6 uses up significiant more space compared to the folder on disk. Copying a folder containing a huge amount of files <=2MB which amounts to ~280GB of size into tmpfs, even with enclave_size=1024GB results in OOM. See attachment [chaindata.txt](https://github.com/gramineproject/gramine/files/14701915/chaindata.txt) for folder structure.

**Comment by mkow** [comment] 2024-03-22 13:29
The only commit I can see since 1.5 which I think could influence this could be 1ea3e60c2b52430cce04c741f2b79c4dc1316ff8, assuming it introduces some memory leak. I didn't see anything other related to tmpfs, but maybe I just missed something... Could you check if this is the commit causing the regression?
If not, could you do `git bisect` to find the culprit? (assuming one run doesn't take too much time)

**Comment by dimakuv** [comment] 2024-04-02 10:15
@lead4good Any progress on debugging this? I don't see anything special in the https://github.com/gramineproject/gramine/commit/1ea3e60c2b52430cce04c741f2b79c4dc1316ff8 commit.

I also don't understand how tmpfs (which uses buffers in enclave memory) relates to the file sizes in database folders. Or do I misunderstand your application and which files exactly are increased in size?

**Comment by dimakuv** [comment] 2024-09-25 07:43
We haven't observed this issue anywhere else, and there was no follow up for the last several months from the topic starter.

I will close this issue. @fnerdman Feel free to re-open it if you still experience this issue and have more data to share with us.

**Closed by dimakuv** 2024-09-25 07:43 UTC
