### ISSUE TITLE
Enable 2-step signing in gramine sign tool

### ISSUE THREAD

**Issue by billionairiam** [gramineproject/gramine#698] opened 2022-06-29 10:17 UTC
## Description of the problem
**The 2-step signing process protects the signing key in a separate facility. **

1. First step: At the end of the enclave build process, the signing tool generates the enclave signing material. The ISV takes the enclave signing material file to an external signing platform/facility where the private key is stored, signs the signing material file, and takes the resulting signature file back to the build platform.

2. Second step: The ISV runs the signing tool with the catsig command providing the necessary information at the command line to add the hash of the public key and signature to the enclave’s metadata section.

**Comment by boryspoplawski** [comment] 2022-06-29 11:13
Duplicate of https://github.com/gramineproject/gramine/issues/11

**Closed by boryspoplawski** 2022-06-29 11:13 UTC
