### ISSUE TITLE
WebAssembly.instantiate():Out of memory

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#934] opened 2022-09-27 09:23 UTC
load wasm in nodejs would always get error as the title(error not only for one special wasm,but for all wasm modules which be used by me).

for example code:

```
var tfjs=require("@tensorflow/tfjs");
var tfjsWasmBackend= require("@tensorflow/tfjs-backend-wasm");
await tfjs.setBackend("wasm");

```

gramine version: 1.2
host linux env: centos8 x64
docker os which gramine-sgx run in: ubuntu20.04 x64
enclave memory size:4GB
nodejs:version 18.4 x64

**Comment by dimakuv** [comment] 2022-09-27 09:35
Duplicate of https://github.com/gramineproject/gramine/issues/927.

Unfortunately, we're currently unaware how to solve this problem. It seems like some hard-coded logic in WebAssembly which is not supported by the current Intel SGX hardware, and Gramine cannot circumvent this.

**Closed by dimakuv** 2022-09-27 09:35 UTC

**Comment by mccoysc** [comment] 2022-09-27 09:52
@dimakuv this is the feature "proto_noreserve".
it means "reserve" a range of memory address space,no need any real memory.and may be later,they can re-call mmap to commit it to real memory.
it's not caused by sgx hardware feature.
maybe you can implement it in mmap?

**Comment by dimakuv** [comment] 2022-09-27 10:03
@mccoysc Please move the discussion to #927. It's better to discuss in one place, rather then it two different (but related) ones.

I understand what you mean, and we already had a brief discussion with @boryspoplawski in #927. Please see there.
