### ISSUE TITLE
Golang netpoll panic for gramine sgx

### ISSUE THREAD

**Issue by Simon-aikuier** [gramineproject/gramine#653] opened 2022-06-15 02:44 UTC
I have a complex application about golang. Its main function is to read data from the database, process by service and send results via kafa. when i test the process service in gramine sgx, it will happen some panics. This process service can work well on normal linux system. So i report this problem and want to know whether gramine can run complex golang applications and whether there are restrictions.

1. SGX Device: 16Core + 16G normal memory + 16G encrypted memory

2. gramie version: 1.1

3.  Manifest:(I test different parameter combinations)
loader.pal_internal_mem_size = "256M"/"1024M"
sys.stack.size = "8M"/"32M"/"64M"
sys.brk.max_size = "8M"/"32M"/64M
sgx.enclave_size = "4096M"/"8192M"/"16382M"/"32768M"
sgx.thread_num = 128/256/512/1024

4. start service and test 1w datas.

5. it will happen panic some time, seems in go routine. The service will use a lot of go routine for data process.

a) panic 1: many panic callstacks, this is the last one
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe35fa6]
goroutine 263 [running]:
gorm.io/gorm.(*DB).getInstance(0x0, 0x18)
        /root/go/pkg/mod/gorm.io/gorm@v1.21.16/gorm.go:355 +0x26
gorm.io/gorm.(*DB).Raw(0x0, 0x1425d10, 0x29b, 0x17087d8d8, 0x1, 0x1, 0x0)
        /root/go/pkg/mod/gorm.io/gorm@v1.21.16/chainable_api.go:296 +0x45

b) panic 2: many panic callstacks, this is the last one
runtime: netpollBreak write failed with 13
fatal error: runtime: netpollBreak write failed
goroutine 4 [running]:
runtime.throw(0x13fa229, 0x22)
        /usr/go/src/runtime/panic.go:1117 +0x72 fp=0x22407be98 sp=0x22407be68 pc=0x43a052
runtime.netpollBreak()
        /usr/go/src/runtime/netpoll_epoll.go:96 +0xe8 fp=0x22407bed0 sp=0x22407be98 pc=0x4358a8
runtime.wakeNetPoller(0x16f8360d562a0c4b)
        /usr/go/src/runtime/proc.go:2952 +0x38 fp=0x22407bee0 sp=0x22407bed0 pc=0x442cb8
runtime.modtimer(0x2240b0000, 0x16f8360d562a0c4b, 0x0, 0x1436048, 0x0, 0x0, 0x0, 0x1436200)
        /usr/go/src/runtime/time.go:492 +0x2dc fp=0x22407bf20 sp=0x22407bee0 pc=0x45b43c
runtime.resettimer(...)
        /usr/go/src/runtime/time.go:544
time.resetTimer(...)
        /usr/go/src/runtime/time.go:229
runtime.scavengeSleep(0x1fcdb, 0xfffffffffe470560)
        /usr/go/src/runtime/mgcscavenge.go:237 +0x8c fp=0x22407bf78 sp=0x22407bf20 pc=0x42498c
runtime.bgscavenge(0x2240a4000)
        /usr/go/src/runtime/mgcscavenge.go:366 +0x1e5 fp=0x22407bfd8 sp=0x22407bf78 pc=0x424be5
runtime.goexit()
        /usr/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0x22407bfe0 sp=0x22407bfd8 pc=0x473d81
created by runtime.gcenable
        /usr/go/src/runtime/mgc.go:218 +0x7e

c) when i open sgx.rpc_thread_num to improve performance, the service start will hung in network communications.

**Comment by dimakuv** [comment] 2022-06-15 11:25
@Simon-aikuier Looks like some problems in network polling. I'm not aware of this issue/bug, but generally Go applications typically work fine in Gramine.

Could I ask you to try this PR: https://github.com/gramineproject/gramine/pull/579 ? It imrpoves the networking subsystem in Gramine, and hopefully your app will be more stable. We will merge this PR some time soon.

**Comment by boryspoplawski** [comment] 2022-06-15 13:11
b) is duplicate of https://github.com/gramineproject/gramine/issues/261 and will be fixed by #579. For the rest I have no idea, there is no meaningful information there.

**Comment by Simon-aikuier** [comment] 2022-06-16 00:16
> b) is duplicate of #261 and will be fixed by #579. For the rest I have no idea, there is no meaningful information there.

Thanks, i will try it as soon and feedback more information.

**Comment by boryspoplawski** [comment] 2022-06-17 21:47
@Simon-aikuier  #579 was just merged, so you can try the newest master.

**Comment by Simon-aikuier** [comment] 2022-06-20 02:59
> @Simon-aikuier #579 was just merged, so you can try the newest master.

ok, thanks. I will try the newest master this week.

**Comment by Simon-aikuier** [comment] 2022-06-23 07:59
> @Simon-aikuier #579 was just merged, so you can try the newest master.

I have test on master, commit: 63d8dca. But my service start failed because of network problems when it pull config from config service via http. It seems like the problem c) i reported before on gramine v1.1, but i didn't open sgx.rpc_thread_num. 

some trace info:
[P1:T7:xxx-service] trace: ---- shim_nanosleep([0,20000], 0) ...
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6cb0) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0
[P1:T1:xxx-service] trace: ---- return from shim_nanosleep(...) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0
[P1:T1:xxx-service] trace: ---- shim_futex(0x1e3cf30, FUTEX_PRIVATE|FUTEX_WAIT, 0, 0, 0, 0) ...
[P1:T7:xxx-service] trace: ---- return from shim_nanosleep(...) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0
[P1:T7:xxx-service] trace: ---- shim_clock_gettime(1, 0x10d32cd20) = 0x0
[P1:T7:xxx-service] trace: ---- shim_clock_gettime(1, 0x10d32cd20) = 0x0
[P1:T7:xxx-service] trace: ---- shim_nanosleep([0,20000], 0) ...
[P1:T17:xxx-service] trace: ---- shim_write(1, 0x108901000, 0x133) ...
2022-06-22 14:56:36.909 ERROR   config.go:74 [config.Get]PullConfig failed, err=Post "http://xxx.xxx.com:port/ConfigService/PullReq": dial tcp: lookup xxx.xxx.com on *.*.*.*: dial udp *.*.*.*: setsockopt: protocol not available

[P1:T17:xxx-service] trace: ---- return from shim_write(...) = 0x133
[P1:T17:xxx-service] trace: ---- shim_futex(0x1e3cf30, FUTEX_PRIVATE|FUTEX_WAKE, 1, 0, 0, 0) ...
[P1:T17:xxx-service] trace: ---- return from shim_futex(...) = 0x1
[P1:T7:xxx-service] trace: ---- return from shim_nanosleep(...) = 0x0
[P1:T1:xxx-service] trace: ---- return from shim_futex(...) = 0x0
[P1:T7:xxx-service] trace: ---- shim_clock_gettime(1, 0x10d32cd20) = 0x0
[P1:T1:xxx-service] trace: ---- shim_clock_gettime(1, 0xfffff940) = 0x0
[P1:T7:xxx-service] trace: ---- shim_clock_gettime(1, 0x10d32cd20) = 0x0
[P1:T1:xxx-service] trace: ---- shim_nanosleep([0,3000], 0) ...
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0
[P1:T7:xxx-service] trace: ---- shim_nanosleep([0,20000], 0) ...
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0
[P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0

**Comment by Simon-aikuier** [comment] 2022-06-23 08:05
> > @Simon-aikuier #579 was just merged, so you can try the newest master.
> 
> I have test on master, commit: [63d8dca](https://github.com/gramineproject/gramine/commit/63d8dcaa66f8ee0a4462fca58055a4057821eeb1). But my service start failed because of network problems when it pull config from config service via http. It seems like the problem c) i reported before on gramine v1.1, but i didn't open sgx.rpc_thread_num. On gramine v1.1, my service can start well, only failed after i open sgx.rpc_thread_num. But on master 63d8dca, my service can not start, so there is no way to verify problem b) for now.
> 
> some trace info: [P1:T7:xxx-service] trace: ---- shim_nanosleep([0,20000], 0) ... [P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6cb0) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0 [P1:T1:xxx-service] trace: ---- return from shim_nanosleep(...) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0 [P1:T1:xxx-service] trace: ---- shim_futex(0x1e3cf30, FUTEX_PRIVATE|FUTEX_WAIT, 0, 0, 0, 0) ... [P1:T7:xxx-service] trace: ---- return from shim_nanosleep(...) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0 [P1:T7:xxx-service] trace: ---- shim_clock_gettime(1, 0x10d32cd20) = 0x0 [P1:T7:xxx-service] trace: ---- shim_clock_gettime(1, 0x10d32cd20) = 0x0 [P1:T7:xxx-service] trace: ---- shim_nanosleep([0,20000], 0) ... [P1:T17:xxx-service] trace: ---- shim_write(1, 0x108901000, 0x133) ... 2022-06-22 14:56:36.909 ERROR config.go:74 [config.Get]PullConfig failed, err=Post "http://xxx.xxx.com:port/ConfigService/PullReq": dial tcp: lookup xxx.xxx.com on _._._._: dial udp _._._._: setsockopt: protocol not available
> 
> [P1:T17:xxx-service] trace: ---- return from shim_write(...) = 0x133 [P1:T17:xxx-service] trace: ---- shim_futex(0x1e3cf30, FUTEX_PRIVATE|FUTEX_WAKE, 1, 0, 0, 0) ... [P1:T17:xxx-service] trace: ---- return from shim_futex(...) = 0x1 [P1:T7:xxx-service] trace: ---- return from shim_nanosleep(...) = 0x0 [P1:T1:xxx-service] trace: ---- return from shim_futex(...) = 0x0 [P1:T7:xxx-service] trace: ---- shim_clock_gettime(1, 0x10d32cd20) = 0x0 [P1:T1:xxx-service] trace: ---- shim_clock_gettime(1, 0xfffff940) = 0x0 [P1:T7:xxx-service] trace: ---- shim_clock_gettime(1, 0x10d32cd20) = 0x0 [P1:T1:xxx-service] trace: ---- shim_nanosleep([0,3000], 0) ... [P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0 [P1:T7:xxx-service] trace: ---- shim_nanosleep([0,20000], 0) ... [P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(0, 0x101ff6dd0) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0 [P1:T17:xxx-service] trace: ---- shim_clock_gettime(1, 0x101ff6dd0) = 0x0

**Comment by dimakuv** [comment] 2022-06-23 08:14
I guess we collected all the Pokemons with these unsupported `setsockopt()` :)

@Simon-aikuier I guess you will also need the PR https://github.com/gramineproject/gramine/pull/678.

**Comment by Simon-aikuier** [comment] 2022-06-23 09:11
> I guess we collected all the Pokemons with these unsupported `setsockopt()` :)
> 
> @Simon-aikuier I guess you will also need the PR #678.

Thanks for your prompt reply. I lookup the trace log, and find the error info as follow:
[P1:T17:xxx-service] trace: ---- shim_setsockopt(3, 1, 6, 0x10884e3d8, 4) = -92 

It looks same with #673. Can it prove to be the same problem?

**Comment by Simon-aikuier** [comment] 2022-06-23 11:15
> I guess we collected all the Pokemons with these unsupported `setsockopt()` :)
> 
> @Simon-aikuier I guess you will also need the PR #678.

I have test #678, sorry to say that but it can not solve my service problem. The trace infos on #678 as follow:

1. some trace infos before and after the error:
[::] debug: Gramine was built from commit: 2542b4a0f490e46752013b96bd3622ecba2dbd13
[P1:T1:xxx-service] trace: ---- shim_socket(INET, SOCK_NONBLOCK|SOCK_CLOEXEC|DGRAM, 0) = 0x3
[P1:T1:xxx-service] trace: ---- shim_setsockopt(3, 1, 6, 0x1a83d43d8, 4) = -92
[P1:T1:xxx-service] trace: ---- shim_close(3) = 0x0
[P1:T15:xxx-service] trace: ---- shim_socket(INET, SOCK_NONBLOCK|SOCK_CLOEXEC|DGRAM, 0) = 0x3
[P1:T1:xxx-service] trace: ---- shim_futex(0x1a8100150, FUTEX_PRIVATE|FUTEX_WAKE, 1, 0, 0, 0) ...
[P1:T15:xxx-service] trace: ---- shim_setsockopt(3, 1, 6, 0x1a83d03d8, 4) = -92
[P1:T1:xxx-service] trace: ---- return from shim_futex(...) = 0x1
[P1:T10:xxx-service] trace: ---- return from shim_futex(...) = 0x0
[P1:T15:xxx-service] trace: ---- shim_close(3) = 0x0
[P1:T1:xxx-service] trace: ---- shim_futex(0x1a8100150, FUTEX_PRIVATE|FUTEX_WAKE, 1, 0, 0, 0) ...
[P1:T10:xxx-service] trace: ---- shim_futex(0x1a8100150, FUTEX_PRIVATE|FUTEX_WAIT, 0, 0, 0, 0) ...
[P1:T1:xxx-service] trace: ---- return from shim_futex(...) = 0x0
[P1:T10:xxx-service] trace: ---- return from shim_futex(...) = -11
[P1:T15:xxx-service] trace: ---- shim_futex(0x1a850c150, FUTEX_PRIVATE|FUTEX_WAIT, 0, 0, 0, 0) ...
[P1:T10:xxx-service] trace: ---- shim_futex(0x1a8100150, FUTEX_PRIVATE|FUTEX_WAIT, 0, 0, 0, 0) ...
[P1:T1:xxx-service] trace: ---- shim_write(1, 0x1a86a2400, 0x133) ...
2022-06-23 18:58:14.966 ERROR   config.go:74 [config.Get]PullConfig failed, err=Post "http://xxx.xxx.com:8080/ConfigService/PullReq": dial tcp: lookup xxx.xxx.com on 9.149.116.44:53: dial udp 9.149.116.44:53: setsockopt: protocol not available
[P1:T1:xxx-service] trace: ---- return from shim_write(...) = 0x133
[P1:T1:xxx-service] trace: ---- shim_futex(0x1a8100150, FUTEX_PRIVATE|FUTEX_WAKE, 1, 0, 0, 0) ...
[P1:T1:xxx-service] trace: ---- return from shim_futex(...) = 0x1
[P1:T10:xxx-service] trace: ---- return from shim_futex(...) = 0x0
[P1:T10:xxx-service] trace: ---- shim_futex(0x1a850c150, FUTEX_PRIVATE|FUTEX_WAKE, 1, 0, 0, 0) ...
[P1:T10:xxx-service] trace: ---- return from shim_futex(...) = 0x1
[P1:T15:xxx-service] trace: ---- return from shim_futex(...) = 0x0

2. return -92 trace infos:
[P1:T1:xxx-service] trace: ---- shim_setsockopt(3, 1, 6, 0x1a83d43d8, 4) = -92
[P1:T10:xxx-service] trace: ---- shim_setsockopt(7, 1, 6, 0x1a86263d8, 4) = -92
[P1:T16:xxx-service] trace: ---- shim_setsockopt(3, 6, 5, 0x1a8615c44, 4) = -92
[P1:T17:xxx-service] trace: ---- shim_setsockopt(8, 6, 5, 0x1a88b4c44, 4) = -92
[P1:T13:xxx-service] trace: ---- shim_setsockopt(9, 6, 5, 0x1a85f5c44, 4) = -92
[P1:T17:xxx-service] trace: ---- shim_setsockopt(11, 6, 5, 0x1a808dc44, 4) = -92
[P1:T18:xxx-service] trace: ---- shim_setsockopt(10, 6, 5, 0x1a8613c44, 4) = -92

3. shim_setsockopt trace infos on gramine v1.1 which my service can start normally:
[P1:T8:xxx-service] trace: ---- shim_setsockopt(8, 1, 6, 0x12c02c3d8, 4) = 0x0
[P1:T17:xxx-service] trace: ---- shim_setsockopt(9, 1, 6, 0x12c0283d8, 4) = 0x0
[P1:T16:xxx-service] trace: ---- shim_setsockopt(7, 6, 1, 0x12c9574c4, 4) = 0x0
[P1:T16:xxx-service] trace: ---- shim_setsockopt(7, 1, 9, 0x12c9577ac, 4) = 0x0
[P1:T16:xxx-service] trace: ---- shim_setsockopt(7, 6, 5, 0x12c95779c, 4) = -92
[P1:T16:xxx-service] trace: ---- shim_setsockopt(8, 6, 1, 0x12c49aeac, 4) = 0x0
[P1:T16:xxx-service] trace: ---- shim_setsockopt(8, 1, 9, 0x12c49b194, 4) = 0x0
[P1:T16:xxx-service] trace: ---- shim_setsockopt(8, 6, 5, 0x12c49b184, 4) = -92
[P1:T16:xxx-service] trace: ---- shim_setsockopt(8, 1, 9, 0x12c49b26c, 4) = 0x0
[P1:T15:xxx-service] trace: ---- shim_setsockopt(10, 6, 1, 0x12c49aeb4, 4) = 0x0
[P1:T15:xxx-service] trace: ---- shim_setsockopt(10, 1, 9, 0x12c49b19c, 4) = 0x0
[P1:T15:xxx-service] trace: ---- shim_setsockopt(10, 6, 5, 0x12c49b18c, 4) = -92
[P1:T15:xxx-service] trace: ---- shim_setsockopt(10, 1, 9, 0x12c49b274, 4) = 0x0
[P1:T9:xxx-service] trace: ---- shim_setsockopt(11, 6, 1, 0x12c976b7c, 4) = 0x0
[P1:T9:xxx-service] trace: ---- shim_setsockopt(11, 1, 9, 0x12c976e64, 4) = 0x0
[P1:T9:xxx-service] trace: ---- shim_setsockopt(11, 6, 5, 0x12c976e54, 4) = -92
[P1:T23:xxx-service] trace: ---- shim_setsockopt(11, 6, 1, 0x12c97ab7c, 4) = 0x0
[P1:T23:xxx-service] trace: ---- shim_setsockopt(11, 1, 9, 0x12c97ae64, 4) = 0x0
[P1:T23:xxx-service] trace: ---- shim_setsockopt(11, 6, 5, 0x12c97ae54, 4) = -92
[P1:T23:xxx-service] trace: ---- shim_setsockopt(11, 6, 1, 0x12cc16b7c, 4) = 0x0
[P1:T23:xxx-service] trace: ---- shim_setsockopt(11, 1, 9, 0x12cc16e64, 4) = 0x0
[P1:T23:xxx-service] trace: ---- shim_setsockopt(11, 6, 5, 0x12cc16e54, 4) = -92
[P1:T17:xxx-service] trace: ---- shim_setsockopt(13, 6, 1, 0x12cae8cd4, 4) = 0x0
[P1:T17:xxx-service] trace: ---- shim_setsockopt(13, 1, 9, 0x12cae8fbc, 4) = 0x0
[P1:T17:xxx-service] trace: ---- shim_setsockopt(13, 6, 5, 0x12cae8fac, 4) = -92
[P1:T23:xxx-service] trace: ---- shim_setsockopt(15, 1, 6, 0x12ce103d8, 4) = 0x0
[P1:T15:xxx-service] trace: ---- shim_setsockopt(16, 1, 6, 0x12ce0c3d8, 4) = 0x0
[P1:T23:xxx-service] trace: ---- shim_setsockopt(3, 6, 1, 0x12c9754c4, 4) = 0x0
[P1:T23:xxx-service] trace: ---- shim_setsockopt(3, 1, 9, 0x12c9757ac, 4) = 0x0
[P1:T23:xxx-service] trace: ---- shim_setsockopt(3, 6, 5, 0x12c97579c, 4) = -92
[P1:T12:xxx-service] trace: ---- shim_setsockopt(15, 6, 1, 0x12c79696c, 4) = 0x0
[P1:T12:xxx-service] trace: ---- shim_setsockopt(15, 1, 9, 0x12c796c54, 4) = 0x0
[P1:T12:xxx-service] trace: ---- shim_setsockopt(15, 6, 5, 0x12c796c44, 4) = -92
[P1:T16:xxx-service] trace: ---- shim_setsockopt(17, 6, 1, 0x12c08f96c, 4) = 0x0
[P1:T16:xxx-service] trace: ---- shim_setsockopt(17, 1, 9, 0x12c08fc54, 4) = 0x0
[P1:T16:xxx-service] trace: ---- shim_setsockopt(17, 6, 5, 0x12c08fc44, 4) = -92
[P1:T17:xxx-service] trace: ---- shim_setsockopt(18, 6, 1, 0x12c79396c, 4) = 0x0
[P1:T17:xxx-service] trace: ---- shim_setsockopt(18, 1, 9, 0x12c793c54, 4) = 0x0
[P1:T17:xxx-service] trace: ---- shim_setsockopt(18, 6, 5, 0x12c793c44, 4) = -92
[P1:T15:xxx-service] trace: ---- shim_setsockopt(3, 6, 1, 0x12cb8696c, 4) = 0x0
[P1:T15:xxx-service] trace: ---- shim_setsockopt(3, 1, 9, 0x12cb86c54, 4) = 0x0
[P1:T15:xxx-service] trace: ---- shim_setsockopt(3, 6, 5, 0x12cb86c44, 4) = -92
[P1:T18:xxx-service] trace: ---- shim_setsockopt(11, 6, 1, 0x12cb8196c, 4) = 0x0
[P1:T18:xxx-service] trace: ---- shim_setsockopt(11, 1, 9, 0x12cb81c54, 4) = 0x0
[P1:T18:xxx-service] trace: ---- shim_setsockopt(11, 6, 5, 0x12cb81c44, 4) = -92

**Comment by dimakuv** [comment] 2022-06-23 11:20
So the unsupported options are `1, 9`, `6, 1`, `6, 5`. @boryspoplawski Could you check what these are?

**Comment by Simon-aikuier** [comment] 2022-06-24 15:19
> `1,6` is `SOL_SOCKET, SO_BROADCAST`, `6,5` is `IPPROTO_TCP, TCP_KEEPINTVL`

@boryspoplawski @dimakuv 
Thanks for your checking. So how to solve this problem? it seems to be common options, and the service can be started normally on gramine v1.1.

**Comment by mkow** [comment] 2022-06-27 10:24
> in this GitHub issue, `SO_BROADCAST` is set on UDP (datagram) sockets, so it is not just a no-op operation

It's exactly the opposite - because it's set on UDP, it _has_ effect. It's a no-op on TCP.

**Comment by boryspoplawski** [comment] 2022-06-27 10:44
We should probably add support for `SO_BROADCAST` (I guess a simple passthrough would be fine here).
Not sure what to do with `TCP_KEEPINTVL`. Actually we can ignore it for now - as seen in log from v1.1 this app starts fine even with this `setsockopt` failing.

**Comment by dimakuv** [comment] 2022-06-27 10:56
>> in this GitHub issue, SO_BROADCAST is set on UDP (datagram) sockets, so it is not just a no-op operation

> It's exactly the opposite - because it's set on UDP, it has effect. It's a no-op on TCP.

That's what I wrote. But my sentence had too many "not"s, I guess :)

I agree with @boryspoplawski's assessment.

**Comment by boryspoplawski** [comment] 2022-06-27 17:55
@Simon-aikuier please try https://github.com/gramineproject/gramine/pull/686

**Comment by Simon-aikuier** [comment] 2022-06-29 07:31
> @Simon-aikuier please try #686
@boryspoplawski 
Thanks for fix. I test my service on #686. 1) it can start normally. 2) it sees the c) problem also solved after i open sgx.rpc_thread_num.

For the b) stable problem, i need some time to test it. I will feedback the result as soon. Thanks.

**Comment by Simon-aikuier** [comment] 2022-07-13 01:23
> > @Simon-aikuier please try #686
> 
> @boryspoplawski Thanks for fix. I test my service on #686. 1) it can start normally. 2) it seems the c) problem also solved after i open sgx.rpc_thread_num.
> 
> For the b) stable problem, i need some time to test it on #579. I will feedback the result as soon. Thanks.

@dimakuv @boryspoplawski 
I have test #579, the problem b) seems ok. Thanks for your help.

For now it will happen golang runtime timer panic with probability, but i have no more useful trace information. So do i need to close this issue first and open a new issue after i get more information? Do you have any better suggestion?

golang runtime timer panic as follow:

fatal error: timer when must be positive
goroutine 4 [running]:
runtime.throw(0x13f0b00, 0x1b)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xf007bee0 sp=0xf007beb0 pc=0x43a032
runtime.modtimer(0xf00b0000, 0x96fd4d1fbad07498, 0x0, 0x1436d20, 0x0, 0x0, 0x0, 0x1436f00)
        /usr/local/go/src/runtime/time.go:425 +0x4be fp=0xf007bf20 sp=0xf007bee0 pc=0x45b79e
runtime.resettimer(...)
        /usr/local/go/src/runtime/time.go:539
time.resetTimer(...)
        /usr/local/go/src/runtime/time.go:229
runtime.scavengeSleep(0x8000000000000000, 0xffffffffff676980)
        /usr/local/go/src/runtime/mgcscavenge.go:237 +0x8c fp=0xf007bf78 sp=0xf007bf20 pc=0x42498c
runtime.bgscavenge(0xf00a4000)
        /usr/local/go/src/runtime/mgcscavenge.go:366 +0x1e5 fp=0xf007bfd8 sp=0xf007bf78 pc=0x424be5
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xf007bfe0 sp=0xf007bfd8 pc=0x473dc1
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:218 +0x7e

**Comment by dimakuv** [comment] 2022-07-13 07:24
> For now it will happen golang runtime timer panic with probability, but i have no more useful trace information. So do i need to close this issue first and open a new issue after i get more information? Do you have any better suggestion?

Yes, let's close this issue. It was about network-related problems. Now your new Golang issue seems to be about timer-related problems.

I would recommend to debug/analyze this new timer-related issue a bit more, come up with a quick reproducer code, and create a new GitHub issue.

**Closed by dimakuv** 2022-07-13 07:24 UTC
