### ISSUE TITLE
Nginx with multiple workers reports "Address already in use" and failed to start under gramine-direct

### ISSUE THREAD

**Issue by shenyuchenx** [gramineproject/gramine#238] opened 2021-11-22 05:54 UTC
## Description of the problem
Nginx with multiple workers reports "Address already in use" and failed to start under gramine-direct.

## Steps to reproduce

0. Set up host environment

# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

# uname -a
Linux icx-10 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

1. install gramine from the repo 

# cat /etc/apt/sources.list.d/gramine.list
deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ stable main

# apt list |grep gramine

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gramine-dcap/stable 1.0-1 amd64
gramine-oot/stable 1.0-1 amd64
gramine/stable,now 1.0-1 amd64 [installed]

2. run gramine-direct

# gramine-direct multi -c /work/shenyc/multi/conf/gramine.conf

multi.manifest:
```
fs.mount.lib.type = "chroot"
fs.mount.lib.path = "/lib"

# ubuntu 20.04, apt version
fs.mount.lib.uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc"
sgx.allowed_files.lib = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc"
loader.preload = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"

fs.mount.lib64.type = "chroot"
fs.mount.lib64.path = "/lib64"
fs.mount.lib64.uri = "file:/usr/lib/x86_64-linux-gnu"
sgx.allowed_files.lib64 = "file:/usr/lib/x86_64-linux-gnu"

fs.mount.usr.type = "chroot"
fs.mount.usr.path = "/usr"
fs.mount.usr.uri = "file:/usr"
sgx.allowed_files.usr = "file:/usr"

loader.env.LD_LIBRARY_PATH = "/lib:/lib64:/usr/lib:/usr/lib64"

libos.entrypoint = "/work/shenyc/dist/nginx/sbin/nginx"

loader.insecure__use_cmdline_argv = true
loader.insecure__disable_aslr = true

sgx.enclave_size = "512M"
sgx.nonpie_binary = true

fs.mount.dist.type = "chroot"
fs.mount.dist.path = "/work/shenyc"
fs.mount.dist.uri = "file:/work/shenyc"
sgx.allowed_files.dist = "file:/work/shenyc"

fs.mount.etc.type = "chroot"
fs.mount.etc.path = "/etc"
fs.mount.etc.uri = "file:/etc"
sgx.allowed_files.etc = "file:/etc"

fs.mount.var_lib.type = "chroot"
fs.mount.var_lib.path = "/var/lib"
fs.mount.var_lib.uri = "file:/var/lib"
sgx.allowed_files.var_lib = "file:/var/lib"

fs.mount.stdout.type = "chroot"
fs.mount.stdout.path = "/dev/stdout"
fs.mount.stdout.uri = "file:/dev/stdout"
sgx.allowed_files.stdout = "file:/dev/stdout"

loader.log_file = "gramine.log"
loader.log_level = "all"

libos.check_invalid_pointers = false
sgx.preheat_enclave = true

sgx.thread_num = 8

sgx.require_avx = true
sgx.require_avx512 = true
```

gramine.conf
```
daemon                             off;
pid                                /work/shenyc/multi/pid/nginx.pid;

worker_processes                   2;
worker_cpu_affinity                1000000000000000000000000 10000000000000000000000000; # cpu24 25


events {
    worker_connections             65535;
}

error_log                          /dev/stdout;

http {

    include                        mime.types;
    default_type                   application/octet-stream;
    sendfile                       on;
    keepalive_timeout              0;

    server {
        listen                     127.0.0.1:8088 ssl reuseport backlog=131072 so_keepalive=off;
        server_name                localhost;

        # access_log                 /dev/stdout;
        access_log                 off;

        ssl_buffer_size            64k;
        ssl_session_tickets        off;
        ssl_verify_client          off;
        lingering_close            off;
        lingering_time             1;
        ssl_protocols              TLSv1.2;
        ssl_certificate            /work/shenyc/multi/apphsm.crt;
        ssl_certificate_key        /work/shenyc/multi/apphsm.key;
        ssl_session_cache          off;
        ssl_session_timeout        0;
        ssl_ciphers                ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            root                   html;
            index                  index.html index.htm;
        }
    }
}
```

The exact commit ID is not very clear to me. From the apt records, it seems:
1.0-1

My installation is installed from deb package by apt via
https://packages.gramineproject.io/

## Expected results
Nginx is expected to keep running and ready to serve requests from clients.

## Actual results
gramine-direct exists, leaving the following error messages:
```
2021/11/22 13:34:34 [emerg] 1#0: bind() to 127.0.0.1:8088 failed (98: Address already in use)
nginx: [emerg] bind() to 127.0.0.1:8088 failed (98: Address already in use)
2021/11/22 13:34:34 [emerg] 1#0: bind() to 127.0.0.1:8088 failed (98: Address already in use)
nginx: [emerg] bind() to 127.0.0.1:8088 failed (98: Address already in use)
2021/11/22 13:34:34 [emerg] 1#0: bind() to 127.0.0.1:8088 failed (98: Address already in use)
nginx: [emerg] bind() to 127.0.0.1:8088 failed (98: Address already in use)
2021/11/22 13:34:34 [emerg] 1#0: bind() to 127.0.0.1:8088 failed (98: Address already in use)
nginx: [emerg] bind() to 127.0.0.1:8088 failed (98: Address already in use)
2021/11/22 13:34:34 [emerg] 1#0: bind() to 127.0.0.1:8088 failed (98: Address already in use)
nginx: [emerg] bind() to 127.0.0.1:8088 failed (98: Address already in use)
2021/11/22 13:34:34 [emerg] 1#0: still could not bind()
```

**Comment by dimakuv** [comment] 2021-11-25 07:26
We need someone to reproduce and check whether this is a real bug in Gramine. I will now set the labels to Bug and P2.

**Comment by shenyuchenx** [comment] 2021-11-25 08:41
I am from intel. My test environment is ready and accessible from the office network, as long as it is convenient for you.

**Comment by Satya1493** [comment] 2021-11-25 10:15
Looks like you're trying to bind Nginx server to port 8088 and it fails to start, complaining the port is already in use. This can happen due to 2 reasons AFAIK.
1. Some other app/server is already running on your system on port 8088? Please check and if this is the case, please use a different port for Nginx.
2. You have an older instance of Nginx already running? You have to kill the Nginx server(along with its worker threads) before you start a new Nginx instance.
Something like **sudo fuser -k 8088/tcp** should help.

**Comment by shenyuchenx** [comment] 2021-11-26 02:05
> Looks like you're trying to bind Nginx server to port 8088 and it fails to start, complaining the port is already in use. This can happen due to 2 reasons AFAIK.
> 
> 1. Some other app/server is already running on your system on port 8088? Please check and if this is the case, please use a different port for Nginx.
> 2. You have an older instance of Nginx already running? You have to kill the Nginx server(along with its worker threads) before you start a new Nginx instance.
>    Something like **sudo fuser -k 8088/tcp** should help.

Thank you for your reply. I am quiet sure 8088 port is not taken by other servers or other nginx instances.
I have verified the 8088 port using netstat. Moreover, as long as I set ```worker_processes``` to 1 (in nginx configuration), the error disappeared.

**Comment by shenyuchenx** [comment] 2021-12-06 11:29
Hi team, I have 2 findings, which might be worthy sharing here.

1. The error is related to the ```reuseport``` option in my nginx config.

With this option, nginx tries to bind the port for each worker. Basically, the process is carried out by 2 steps:

(a) call setsockopt() to set SO_REUSEPORT for the socket, and then
(b) call bind() to do the actual bind operation.

Here, ```SO_REUSEPORT``` is not supported by ```shim_do_setsockopt()``` of Gramine. As a result, only the 1st bind can success and the rest bind operations fail.

2. The error message (98: Address already in use) is somewhat miss leading. This is because ```setsockopt()``` returns 0 even if the option is not supported. In this case, nginx keeps running until ```bind()``` returns a non-zero value.

As far as I can follow, in function ```shim_do_setsockopt()```, in my case, ```hdl->pal_handle``` is ```NULL```, so ```__do_setsockopt()``` is not called and ret is 0. ```__do_setsockopt()``` is not called until nginx invokes ```bind()```. The actual return value of ```__do_setsockopt()``` is not known by nginx, so that nginx can not produce a right error message either.


It would be greatly appreciated if SO_REUSEPORT option of setsockopt() be supported in Gramine. Or do you have any plan for it?

**Comment by mkow** [comment] 2022-02-18 01:21
We plan to do a bigger rework of the whole sockets subsystem very soon, we'll hopefully fix this as part of it.

**Comment by shenyuchenx** [comment] 2022-02-18 02:04
Thank you for your information. I am looking forward to the update.

**Comment by boryspoplawski** [comment] 2022-05-16 12:32
`SO_REUSEPORT` is used mainly (only, at least on Linux?) for load balancing. The problem is that it's not really standard, e.g. Windows doesn't have it (and semantics differ slightly between different OSes). As far as we probably could implement something that works correctly on every PAL, I'm not sure we want - if we cannot achieve even load balancing, then there is no much point in having it...
@shenyuchenx could you check what happens on https://github.com/gramineproject/gramine/pull/579 ? It does not implement reuseport, but it will explicitly return an error from `setsockopt`.

**Comment by boryspoplawski** [comment] 2022-05-16 15:53
As we talked on todays call: no plans to implement `SO_REUSEPORT`. Nginx will probably fallback to some workaround if it detects this flag is not supported. If it does not, then we might rethink this.

**Comment by shenyuchenx** [comment] 2022-05-17 02:38
Thank you for your reply. I will check #579 .

I do respect your decision on support plan. However, this option (reuseport for nginx, accordingly SO_REUSEPORT for socket layer) is broadly used by nginx community. Almost all our users rely on this option.

**Comment by boryspoplawski** [comment] 2022-06-17 21:46
@shenyuchenx DId you check #579? It was just merged, so you can just check the newest master. Let me know if nginx works for you now

**Comment by shenyuchenx** [comment] 2022-06-20 01:21
I did not have time to check it yet. I will let you known as soon as it is checked.

**Comment by mkow** [comment] 2022-11-27 16:33
Closing because of no reply from the reporter + we merged https://github.com/gramineproject/gramine/pull/1031, which probably solves this issue.

**Closed by mkow** 2022-11-27 16:33 UTC
Labels: bug, P: 2
