### ISSUE TITLE
lots of `poll` with final `SIGABRT` and PalProcessExit: Returning exit code 134 (C# net6.0 Web-API)

### ISSUE THREAD

**Issue by ChristopherLenz** [gramineproject/gramine#974] opened 2022-10-13 12:32 UTC
### Description of the problem

Hello everyone,

I've slowly reached the end of my knowledge and my nerves. I'm trying to get a simple example .net web api up and running. In total I've been stuck with 5 or 6 smaller problems and in the end I've always made progress a little bit. Now, unfortunately, I have no more ideas and I have the feeling that Gramine does not harmonize with the .net application.

### Steps to reproduce

1. Containerize a simple .net Web-API
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /source

# copy everything else and build app
COPY aspnetapp/*.csproj .
COPY aspnetapp/. .
RUN dotnet publish -c Debug -o /app -r linux-x64 --self-contained false

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal-amd64
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "my-benchmark-app.dll"]
```
2. With the help of gsc I created a "working" gramine-image
3. Use following `manifest`-file
```
[sgx]
enclave_size = "8G"
thread_num = 32
rpc_thread_num = 16
preheat_enclave = false
nonpie_binary = true
debug = true

[sys]
insecure__allow_eventfd = true

[loader]
pal_internal_mem_size = "128M"
entrypoint = "file:/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/libsysdb.so"
log_level = "all"
argv0_override = "/gramine/app_files/dotnet"
insecure__use_cmdline_argv = true

[fs]
start_dir = "/app/"
[[fs.mounts]]
path = "/tmp"
uri = "file:/tmp"
type = "tmpfs"

[[fs.mounts]]
path = "/etc"
uri = "file:/etc"

[[fs.mounts]]
path = "/usr"
uri = "file:/usr"

[[fs.mounts]]
path = "/lib64"
uri = "file:/lib64"

[[fs.mounts]]
uri = "file:/usr/share/dotnet"
path = "/gramine/app_files"

[libos]
entrypoint = "/gramine/app_files/dotnet"

[loader.env]
DOTNET_GCHeapHardLimit = "0x20000000"
DOTNET_ENVIRONMENT = "Development"
DOTNET_EnableDiagnostics = "1"
CORECLR_ENABLE_PROFILING = "1"
MALLOC_ARENA_MAX = "1"
LD_LIBRARY_PATH = "/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc:/usr/lib/x86_64-linux-gnu:{{library_paths}}"
PATH = "{{env_path}}"
ASPNETCORE_URLS = "http://+:80"
DOTNET_RUNNING_IN_CONTAINER = "true"
DOTNET_VERSION = "6.0.10"
ASPNET_VERSION = "6.0.10"

[fs.root]
type = "chroot"
uri = "file:/"
```
4. run this image. (I used Microsoft Azure for that)
5. I already tried with different combinations of `insecure__allow_eventfd`, `nonpie_binary` and `MALLOC_ARENA_MAX`

### Expected results

The Web-Api works

### Actual results

Full log: https://gist.github.com/ChristopherLenz/7a297598738bda5a1c16eb2bd3964b0d
```
2022-10-13T11:44:07.786774884Z + set -e
2022-10-13T11:44:07.789419081Z ++ find /gramine/meson_build_output/lib -type d -path '*/site-packages'
2022-10-13T11:44:07.789428778Z + export PYTHONPATH=:/gramine/meson_build_output/lib/python3.8/site-packages
2022-10-13T11:44:07.789430768Z + PYTHONPATH=:/gramine/meson_build_output/lib/python3.8/site-packages
2022-10-13T11:44:07.789432524Z ++ find /gramine/meson_build_output/lib -type d -path '*/pkgconfig'
2022-10-13T11:44:07.789434560Z + export PKG_CONFIG_PATH=:/gramine/meson_build_output/lib/x86_64-linux-gnu/pkgconfig
2022-10-13T11:44:07.789438663Z + PKG_CONFIG_PATH=:/gramine/meson_build_output/lib/x86_64-linux-gnu/pkgconfig
2022-10-13T11:44:07.799141137Z + '[' -z '' ']'
2022-10-13T11:44:07.799148462Z + gramine-sgx-get-token --quiet --sig /gramine/app_files/entrypoint.sig --output /gramine/app_files/entrypoint.token
2022-10-13T11:44:07.963157443Z + gramine-sgx /gramine/app_files/entrypoint my-benchmark-app.dll ''
2022-10-13T11:44:07.963176472Z Gramine is starting. Parsing TOML manifest file, this may take some time...
2022-10-13T11:44:36.019119832Z debug: Gramine parsed TOML manifest file successfully
2022-10-13T11:44:36.019805053Z debug: Token file: /gramine/app_files/entrypoint.token
2022-10-13T11:44:36.019918974Z debug: Read dummy DCAP token
2022-10-13T11:44:36.019934893Z debug: Enclave created:
2022-10-13T11:44:36.019937873Z debug:     base:           0x0000000000000000
2022-10-13T11:44:36.019940483Z debug:     size:           0x0000000200000000
2022-10-13T11:44:36.019942969Z debug:     misc_select:    0x00000000
2022-10-13T11:44:36.019945264Z debug:     attr.flags:     0x0000000000000007
2022-10-13T11:44:36.019947619Z debug:     attr.xfrm:      0x00000000000000e7
2022-10-13T11:44:36.019949891Z debug:     ssa_frame_size: 4
2022-10-13T11:44:36.019952299Z debug:     isv_prod_id:    0x00000000
2022-10-13T11:44:36.019954669Z debug:     isv_svn:        0x00000000
2022-10-13T11:44:36.061465310Z debug: Adding pages to SGX enclave, this may take some time...
2022-10-13T11:44:36.066500581Z debug: Adding pages to enclave: 0x1fefb3000-0x200000000 [REG:R--] (manifest) measured
2022-10-13T11:44:36.140480932Z debug: Adding pages to enclave: 0x1feeb3000-0x1fefb3000 [REG:RW-] (ssa) measured

...  (see full log)

2022-10-13T11:45:11.643171952Z [P1:T1:dotnet] trace: ---- return from mmap(...) = 0x7ccce000
2022-10-13T11:45:11.643263885Z [P1:T1:dotnet] trace: ---- mprotect(0x7cd33000, 0x16c000, PROT_NONE) ...
2022-10-13T11:45:11.643278269Z [P1:T1:dotnet] trace: ---- return from mprotect(...) = 0x0
2022-10-13T11:45:11.643281345Z [P1:T1:dotnet] trace: ---- mmap(0x7cd33000, 0xe5000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 61, 0x65000) ...
2022-10-13T11:45:11.646949186Z [P1:T1:dotnet] trace: ---- return from mmap(...) = 0x7cd33000
2022-10-13T11:45:11.647032917Z [P1:T1:dotnet] trace: ---- mmap(0x7ce18000, 0x86000, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 61, 0x14a000) ...
2022-10-13T11:45:11.649155700Z [P1:T1:dotnet] trace: ---- return from mmap(...) = 0x7ce18000
2022-10-13T11:45:11.649229577Z [P1:T1:dotnet] trace: ---- mmap(0x7ce9f000, 0x13000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 61, 0x1d0000) ...
2022-10-13T11:45:11.649600872Z [P1:T1:dotnet] trace: ---- return from mmap(...) = 0x7ce9f000
2022-10-13T11:45:11.649669310Z [P1:T1:dotnet] trace: ---- mmap(0x7ceb2000, 0x11c0, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0x0) ...
2022-10-13T11:45:11.649680962Z [P1:T1:dotnet] trace: ---- return from mmap(...) = 0x7ceb2000
2022-10-13T11:45:11.649683095Z [P1:T1:dotnet] trace: ---- close(61) = 0x0
2022-10-13T11:45:11.649685679Z [P1:T1:dotnet] debug: glibc register library /usr/lib/x86_64-linux-gnu/libicuuc.so.66 loaded at 0x7ccce000
2022-10-13T11:45:11.649974673Z [P1:T1:dotnet] debug: append_r_debug: adding file:/usr/lib/x86_64-linux-gnu/libicuuc.so.66 at 0x7ccce000
2022-10-13T11:45:11.649981074Z [P1:T1:dotnet] trace: ---- openat(AT_FDCWD, "/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc/libicudata.so.66", O_RDONLY|0x80000, 0000) = -2
2022-10-13T11:45:11.663166969Z [P1:T8:dotnet] trace: ---- return from futex(...) = -110
2022-10-13T11:45:11.663270599Z [P1:T8:dotnet] trace: ---- futex(0x7d7376d0, FUTEX_PRIVATE|FUTEX_WAKE, 1, 0, 0x7d737718, 0) ...
2022-10-13T11:45:11.663284718Z [P1:T8:dotnet] trace: ---- return from futex(...) = 0x0
2022-10-13T11:45:11.663287558Z [P1:T8:dotnet] trace: ---- clock_gettime(1, 0x7d382ab0) = 0x0
2022-10-13T11:45:11.663300234Z [P1:T8:dotnet] trace: ---- futex(0x7d737720, FUTEX_PRIVATE|FUTEX_WAIT_BITSET, 0, 0x7d382ab0, 0, -1) ...
2022-10-13T11:45:11.763774179Z [P1:T8:dotnet] trace: ---- return from futex(...) = -110
2022-10-13T11:45:11.764118534Z [P1:T8:dotnet] trace: ---- futex(0x7d7376d0, FUTEX_PRIVATE|FUTEX_WAKE, 1, 0, 0x7d737718, 0) ...
2022-10-13T11:45:11.764180309Z [P1:T8:dotnet] trace: ---- return from futex(...) = 0x0
2022-10-13T11:45:11.764790845Z [P1:T8:dotnet] trace: ---- mprotect(0x87440000, 0x1000, PROT_READ|PROT_WRITE) ...
2022-10-13T11:45:11.764797744Z [P1:T8:dotnet] trace: ---- return from mprotect(...) = 0x0
2022-10-13T11:45:11.764800298Z [P1:T8:dotnet] trace: ---- madvise(0x87440000, 0x1000, MADV_DODUMP) = -38
2022-10-13T11:45:11.764802681Z [P1:T8:dotnet] trace: ---- mprotect(0x87440000, 0x1000, PROT_READ|PROT_WRITE|PROT_EXEC) ...
2022-10-13T11:45:11.764804860Z [P1:T8:dotnet] trace: ---- return from mprotect(...) = 0x0
2022-10-13T11:45:11.764807022Z [P1:T8:dotnet] trace: ---- mprotect(0x87441000, 0x1000, PROT_READ|PROT_WRITE) ...
2022-10-13T11:45:11.764809079Z [P1:T8:dotnet] trace: ---- return from mprotect(...) = 0x0
2022-10-13T11:45:11.764811144Z [P1:T8:dotnet] trace: ---- madvise(0x87441000, 0x1000, MADV_DODUMP) = -38
2022-10-13T11:45:11.764813125Z [P1:T8:dotnet] trace: ---- mprotect(0x87441000, 0x1000, PROT_READ|PROT_WRITE|PROT_EXEC) ...
2022-10-13T11:45:11.764815164Z [P1:T8:dotnet] trace: ---- return from mprotect(...) = 0x0
2022-10-13T11:45:11.764817478Z [P1:T8:dotnet] trace: ---- sched_yield() = 0x0
2022-10-13T11:45:11.764819500Z [P1:T8:dotnet] trace: ---- clock_gettime(1, 0x7d382880) = 0x0
2022-10-13T11:45:11.764821874Z [P1:T8:dotnet] trace: ---- futex(0x7d737720, FUTEX_PRIVATE|FUTEX_WAIT_BITSET, 0, 0x7d382880, 0, -1) ...
2022-10-13T11:45:11.866719786Z [P1:T1:dotnet] trace: ---- openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libicudata.so.66", O_RDONLY|0x80000, 0000) = 0x3d
2022-10-13T11:45:11.867011802Z [P1:T1:dotnet] trace: ---- read(61, 0x80338c78, 0x340) ...
2022-10-13T11:45:11.867029685Z [P1:T1:dotnet] trace: ---- return from read(...) = 0x340
2022-10-13T11:45:11.867033192Z [P1:T1:dotnet] trace: ---- newfstatat(61, "", 0x80338b10, 4096) = 0x0
2022-10-13T11:45:11.867036330Z [P1:T1:dotnet] trace: ---- mmap(0, 0x1ac0010, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 61, 0x0) ...
2022-10-13T11:45:12.009774941Z [P1:T1:dotnet] trace: ---- return from mmap(...) = 0x7b20d000
2022-10-13T11:45:12.010553471Z [P1:T1:dotnet] trace: ---- mmap(0x7b20e000, 0x1000, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 61, 0x1000) ...
2022-10-13T11:45:12.010687604Z [P1:T1:dotnet] trace: ---- return from mmap(...) = 0x7b20e000
2022-10-13T11:45:12.010702641Z [P1:T1:dotnet] trace: ---- mmap(0x7b20f000, 0x1abd000, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 61, 0x2000) ...
2022-10-13T11:45:12.466285231Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:12.466287200Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:12.466304667Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:12.466311164Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:12.466334350Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:12.466347133Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:12.466358458Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1

... many times (see full log)

2022-10-13T11:45:14.316036388Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.316048731Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.316050729Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.316067436Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.316078066Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.316091309Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.316093243Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.318680412Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.318685565Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.318690941Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.318692774Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.318694593Z [P1:T1:dotnet] trace: ---- return from futex(...) = -110
2022-10-13T11:45:14.318696514Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.318698323Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.318701825Z [P1:T1:dotnet] trace: ---- futex(0x7fc5ab70, FUTEX_PRIVATE|FUTEX_WAKE, 1, 0, 0x7fc5abb8, 0) ...
2022-10-13T11:45:14.318703957Z [P1:T1:dotnet] trace: ---- return from futex(...) = 0x0
2022-10-13T11:45:14.318706217Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.318708044Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.318710364Z [P1:T1:dotnet] trace: ---- rt_sigaction([SIGABRT], 0x8033ab20, 0, 0x8) = 0x0
2022-10-13T11:45:14.318767543Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.318769590Z [P1:T1:dotnet] trace: ---- rt_sigprocmask(UNBLOCK, [SIGABRT,], NULL, 0x8) = 0x0
2022-10-13T11:45:14.318771893Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.318774028Z [P1:T1:dotnet] trace: ---- gettid() = 0x1
2022-10-13T11:45:14.318777338Z [P1:T1:dotnet] trace: ---- getpid() = 0x1
2022-10-13T11:45:14.318779273Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.318781149Z [P1:T2:dotnet] trace: ---- poll(0x7f4b2cf8, 1, 1000) ...
2022-10-13T11:45:14.318782955Z [P1:T1:dotnet] trace: ---- tgkill(1, 1, [SIGABRT]) = 0x0
2022-10-13T11:45:14.318784882Z [P1:T1:dotnet] debug: killed by signal 6
2022-10-13T11:45:14.318786759Z [P1:T2:dotnet] trace: ---- return from poll(...) = 0x1
2022-10-13T11:45:14.318788627Z [P1:T3:dotnet] trace: ---- return from read(...) = -512
2022-10-13T11:45:14.318790433Z [P1:T4:dotnet] trace: ---- return from futex(...) = -512
2022-10-13T11:45:14.318792356Z [P1:T8:dotnet] trace: ---- return from futex(...) = -512
2022-10-13T11:45:14.318794170Z [P1:T5:dotnet] trace: ---- return from futex(...) = -512
2022-10-13T11:45:14.318796043Z [P1:T6:dotnet] trace: ---- return from futex(...) = -512
2022-10-13T11:45:14.318798744Z [P1:T8:dotnet] debug: Creating pipe: pipe.srv:248aae68741c2f6494782fbdc900d87937f4b2fdd2d0d0591edea8244cd3bf5c
2022-10-13T11:45:14.318800585Z [P1:T7:dotnet] trace: ---- return from futex(...) = -512
2022-10-13T11:45:14.322990414Z [P1:T1:dotnet] debug: clearing POSIX locks for pid 1
2022-10-13T11:45:14.322996199Z [P1:T1:dotnet] debug: sync client shutdown: closing handles
2022-10-13T11:45:14.322998619Z [P1:T1:dotnet] debug: sync client shutdown: waiting for confirmation
2022-10-13T11:45:14.323000618Z [P1:T1:dotnet] debug: sync client shutdown: finished
2022-10-13T11:45:14.323507636Z [P1:T5:dotnet] debug: Installed async event at 1665661514316366
2022-10-13T11:45:14.323512699Z [P1:T6:dotnet] debug: Installed async event at 1665661514316395
2022-10-13T11:45:14.323514594Z [P1:T7:dotnet] debug: Installed async event at 1665661514316425
2022-10-13T11:45:14.323516507Z [P1:T4:dotnet] debug: Installed async event at 1665661514317402
2022-10-13T11:45:14.323518382Z [P1:T3:dotnet] debug: Installed async event at 1665661514316441
2022-10-13T11:45:14.323520312Z [P1:T2:dotnet] debug: Installed async event at 1665661514322701
2022-10-13T11:45:14.323522247Z [P1:T8:dotnet] debug: Installed async event at 1665661514316357
2022-10-13T11:45:14.323599373Z [P1:libos] debug: IPC worker: exiting worker thread
2022-10-13T11:45:14.323858732Z [P1:T1:dotnet] debug: process 1 exited with status 134
2022-10-13T11:45:14.323863664Z debug: PalProcessExit: Returning exit code 134
2022-10-13T11:45:21.33653975Z  Stream closed EOF for default/pi-conf (pi-conf)
```

### Gramine commit hash

v1.3.1

**Comment by dimakuv** [comment] 2022-10-14 09:10
The problem is somewhere here:
```
2022-10-13T11:45:14.318774028Z [P1:T1:dotnet] trace: ---- gettid() = 0x1
2022-10-13T11:45:14.318777338Z [P1:T1:dotnet] trace: ---- getpid() = 0x1
2022-10-13T11:45:14.318782955Z [P1:T1:dotnet] trace: ---- tgkill(1, 1, [SIGABRT]) = 0x0
2022-10-13T11:45:14.318784882Z [P1:T1:dotnet] debug: killed by signal 6
```

`SIGABRT` almost always indicates that the application found some inconsistent state itself and decided to abort itself. Typically, applications also print some stack trace or some meaningful error message. However, here I don't see that the app writes anything useful (other than "Stream closed EOF").

So the problem is somewhere inside your .NET application -- I guess in what this application expects from Gramine-SGX, but Gramine-SGX doesn't implement this.

---

You seem to use GSC for "graminization" of your original Docker image, but you also create a full-fledged manifest? You're **not supposed** to write the whole manifest -- GSC does it for you (yeah, I know, this is not obvious from the documentation). Typically, the manifest for GSC only contains `sgx.enclave_size` and `sgx.thread_num`, and maybe a couple other options like `eventfd` enabling.

In particular, this snippet from your manifest file is suspicios:
```
[loader.env]
...
LD_LIBRARY_PATH = "/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc:/usr/lib/x86_64-linux-gnu:{{library_paths}}"
PATH = "{{env_path}}"
```

What are these `{{jinja var}}`? Where do you get them from? (Now that I think about it, maybe it is indeed supported by GSC, but like accidentally :)). Are you sure they work correctly?

In general, I don't understand how this manifest file that you show us can correctly work with GSC -- GSC adds most of these fields automatically, so you will have duplicated fields, and technically Gramine should complain about this. How can this work?

**Comment by ChristopherLenz** [comment] 2022-10-14 09:46
Thanks for the answer. At the same time, I'm working on the problem of missing logs on the part of dotnet. But somehow I can't get any more logs out and was hoping that something very obvious would be noticed by gramine.

Regarding the manifest. That's already the manifest, which was generated by gsc. Actually, my plan was to keep gsc out of the problem and to define it more clearly. But apparently it did the exact opposite... :-)

Here is the pre-gsc manifest:
```
sgx.enclave_size = "8G"
sgx.thread_num = 32
sgx.rpc_thread_num = 16
sgx.preheat_enclave = false

sys.insecure__allow_eventfd = true

loader.env.DOTNET_GCHeapHardLimit = "0x20000000"
loader.env.DOTNET_ENVIRONMENT = "Development"
loader.env.DOTNET_EnableDiagnostics = "1"
loader.env.CORECLR_ENABLE_PROFILING = "1"

sgx.nonpie_binary = true
loader.env.MALLOC_ARENA_MAX = "1"
loader.pal_internal_mem_size = "128M"

fs.mounts = [
    { path = "/tmp",              uri = "file:/tmp",        type = "tmpfs" },
    { path = "/etc",              uri = "file:/etc" },
    { path = "/usr",              uri = "file:/usr" },
    { path = "/lib64", uri = "file:/lib64" },
    { uri = "file:/usr/share/dotnet", path = "/gramine/app_files" },
]
```

**Comment by dimakuv** [comment] 2022-10-14 09:56
Ok, now I get it about the manifest.

The manifest looks reasonable, but what is this:
```
fs.mounts = [
    { path = "/tmp",              uri = "file:/tmp",        type = "tmpfs" },
    { path = "/etc",              uri = "file:/etc" },
    { path = "/usr",              uri = "file:/usr" },
    { path = "/lib64", uri = "file:/lib64" },
    { uri = "file:/usr/share/dotnet", path = "/gramine/app_files" },
]
```

Only the first item (`/tmp`) is reasonable, though not required (well, probably required for security reasons, to not keep temporary files in the Docker container in plaintext).

The items `/etc`, `/usr` and `/lib64` seem totally useless, GSC already includes the files under these dirs. Feel free to remove these three items.

The last item is bizzare to me -- what's the point of this, what does it do? Feels wrong. Please remove it, or explain why you need this. (I guess you're attaching a volume to the Docker image at `/usr/share/dotnet`, which may be reasonable, but why do you reflect this volume under `/gramine/app_files/` directory inside Gramine?)

---

If .NET is so unwilling to print debug logs, you can always jump inside the GSC-generated Docker image via `--entrypoint /bin/bash` and try to debug it yourself. For this, you can use GDB.

GSC provides a helpful `gsc build --debug` flag, that will build Gramine in debug mode and ready for GDB. But I imagine that debugging .NET framework is a pain...

**Comment by ChristopherLenz** [comment] 2022-10-14 10:41
Reason for the dotnet-mount was another problem during the start:

```
[P1:T1:dotnet] trace: ---- mprotect(0xe175a000, 0x2000, PROT_READ) ...
[P1:T1:dotnet] trace: ---- return from mprotect(...) = 0x0
[P1:T1:dotnet] trace: ---- prlimit64(0, 3, 0, 0xe17c2870) = 0x0
[P1:T1:dotnet] trace: ---- getrandom(0xe1438198, 0x8, GRND_NONBLOCK) = 0x8
[P1:T1:dotnet] trace: ---- brk(0) = 0xe2551000
[P1:T1:dotnet] trace: ---- brk(0xe2572000) = 0xe2572000
[P1:T1:dotnet] trace: ---- futex(0xe17156bc, FUTEX_PRIVATE|FUTEX_WAKE, 2147483647, 0, 0x1, 202) ...
[P1:T1:dotnet] trace: ---- return from futex(...) = 0x0
[P1:T1:dotnet] trace: ---- futex(0xe17156c8, FUTEX_PRIVATE|FUTEX_WAKE, 2147483647, 0, 0x1, 202) ...
[P1:T1:dotnet] trace: ---- return from futex(...) = 0x0
[P1:T1:dotnet] trace: ---- readlink("/proc", 0xe17c2630, 1023) = -22
[P1:T1:dotnet] trace: ---- readlink("/proc/self", 0xe17c2630, 1023) = 0x1
[P1:T1:dotnet] trace: ---- readlink("/proc/1", 0xe17c2630, 1023) = -22
[P1:T1:dotnet] trace: ---- readlink("/proc/1/exe", 0xe17c2630, 1023) = 0x19
[P1:T1:dotnet] trace: ---- readlink("/gramine", 0xe17c2630, 1023) = -22
[P1:T1:dotnet] trace: ---- readlink("/gramine/app_files", 0xe17c2630, 1023) = -22
[P1:T1:dotnet] trace: ---- readlink("/gramine/app_files/dotnet", 0xe17c2630, 1023) = -22
[P1:T1:dotnet] trace: ---- readlink("/gramine", 0xe17c2630, 1023) = -22
[P1:T1:dotnet] trace: ---- readlink("/gramine/app_files", 0xe17c2630, 1023) = -22
[P1:T1:dotnet] trace: ---- readlink("/gramine/app_files/dotnet", 0xe17c2630, 1023) = -22
A fatal error occurred. The folder [/gramine/app_files/host/fxr] does not exist
[P1:T1:dotnet] trace: ---- access("/gramine/app_files/host/fxr", F_OK) = -2
[P1:T1:dotnet] trace: ---- write(2, 0xe25630c0, 0x4f) ...
[P1:T1:dotnet] trace: ---- return from write(...) = 0x4f
[P1:T1:dotnet] trace: ---- write(2, 0xe1431723, 0x1) ...
[P1:T1:dotnet] trace: ---- return from write(...) = 0x1
[P1:T1:dotnet] debug: ---- exit_group (returning 131)
[P1:T1:dotnet] debug: clearing POSIX locks for pid 1
[P1:T1:dotnet] debug: sync client shutdown: closing handles
[P1:T1:dotnet] debug: sync client shutdown: waiting for confirmation
[P1:T1:dotnet] debug: sync client shutdown: finished
[P1:libos] debug: IPC worker: exiting worker thread
[P1:T1:dotnet] debug: process 1 exited with status 131
debug: PalProcessExit: Returning exit code 131
```

Do you think that could be a consequential error of my (possibly wrong fix via mount)?

**Comment by dimakuv** [comment] 2022-10-14 10:58
Yes, it could be the root cause.

But without knowing what these directories/files are and the context of this execution, I can't give any advice. I have zero clue what `dotnet` is (an executable? a directory with some helper libraries?), and what `fxr/` directory is.

**Comment by ChristopherLenz** [comment] 2022-10-14 11:05
It is a directory with some runtime libraries

<img width="544" alt="image" src="https://user-images.githubusercontent.com/11405586/195831952-c4640b42-4fb8-4c2f-99a2-949b9490331d.png">

this is the gramine folder, where the executable is linked
<img width="506" alt="image" src="https://user-images.githubusercontent.com/11405586/195832259-258267cf-f76b-4422-ac48-2f499bb68498.png">

**Comment by dimakuv** [comment] 2022-10-14 12:24
Ok, this seems to make sense.

Now we're back to the original issue of `SIGABRT`. Unfortunately, we need more information. As I said previously, this should be a result of `abort()` or `assert()` triggerring in the .NET framework (or .NET application itself). Typically .NET should print some error message. Please try to figure out how to print it.

**Comment by nmwael** [comment] 2023-09-06 06:03
Hi, I'm hitting the exact same issue and are picking up the torch. @ChristopherLenz did you solve this? 

From my below error I would expect its just a matter of linking gone wrong..

exhibit from my "error"
`
(libos_parser.c:1628:buf_write_all) [P3:T33:dotnet] trace: ---- readlink("/gramine/app_files/dotnet", 0x78654650, 1023) = -22
A fatal error occurred. The folder [/gramine/app_files/host/fxr] does not exist
(libos_parser.c:1628:buf_write_all) [P3:T33:dotnet] trace: ---- access("/gramine/app_files/host/fxr", F_OK) = -2

`

**Comment by dimakuv** [comment] 2023-09-06 13:35
@nmwael Have you tried adding:
```
fs.mounts = [
    { uri = "file:/usr/share/dotnet", path = "/gramine/app_files" },
]
```

to your GSC manifest file?

See our discussions above.

**Comment by nmwael** [comment] 2023-09-07 05:36
Im looking into that now, I was actually trying to get the dotnet framework to behave reasonably (by explicitly telling it where /host/fxr where located). Java did'nt have the need for quirks like this.. I'll get back with my findings.

**Comment by nmwael** [comment] 2023-09-07 08:00
Im getting this:

```
(libos_init.c:410:libos_init) debug: LibOS loaded at 0xfc181000, ready to initialize
(libos_init.c:561:create_pipe) debug: Creating pipe: pipe.srv:0735db9e2b6a9f7a83bc5f00fd30b5cf38e7461186ec1e5f26e2d2104974b8e1
(libos_fs.c:525:mount_fs) [P1:T1:] debug: mounting "file:/" (chroot) under /
(libos_fs.c:525:mount_fs) [P1:T1:] debug: mounting "proc" (pseudo) under /proc
(libos_fs.c:525:mount_fs) [P1:T1:] debug: mounting "dev" (pseudo) under /dev
(libos_fs.c:525:mount_fs) [P1:T1:] debug: mounting "dev:tty" (chroot) under /dev/tty
(libos_fs.c:525:mount_fs) [P1:T1:] debug: mounting "sys" (pseudo) under /sys
(libos_fs.c:525:mount_fs) [P1:T1:] debug: mounting "file:/usr/share/dotnet" (chroot) under /gramine/app_files
(libos_fs.c:525:mount_fs) [P1:T1:] debug: mounting "(null)" (tmpfs) under /cloudkeywork
(libos_fs.c:525:mount_fs) [P1:T1:] debug: mounting "emulated-etc-resolv-conf" (pseudo) under /etc/resolv.conf
(libos_init.c:436:libos_init) [P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)
```

**I would expect that the contents of the directory (/usr/share/dotnet) was mounted in /gramine/app_files not replacing it?**

Content of my template 
```
sys.insecure__allow_eventfd = true
sgx.enclave_size = "4G"
sgx.max_threads = 64
sgx.remote_attestation = "dcap"
sys.stack.size = "1M"
sys.brk.max_size = "1M"
sys.enable_extra_runtime_domain_names_conf = true
sgx.trusted_files = ["file:/usr/share/dotnet/"]
fs.mounts = [{ uri = "file:/usr/share/dotnet", path = "/gramine/app_files" }]
```
I think the sgx.trusted_files entry is not needed.

**Comment by nmwael** [comment] 2023-09-07 08:19
changing to 
```
sys.insecure__allow_eventfd = true
sgx.enclave_size = "4G"
sgx.max_threads = 64
sgx.remote_attestation = "dcap"
sys.stack.size = "1M"
sys.brk.max_size = "1M"
sys.enable_extra_runtime_domain_names_conf = true
fs.mounts = [{ uri = "file:/usr/share/dotnet/host", path = "/gramine/app_files/host" },{ uri = "file:/usr/share/dotnet/shared", path = "/gramine/app_files/shared" }]
```
got me further.. I just need to check how the actual app responds.

**Comment by dimakuv** [comment] 2023-09-07 08:31
> I would expect that the contents of the directory (/usr/share/dotnet) was mounted in /gramine/app_files not replacing it?

Oh, you are right, the contents get **replaced** when you mount the whole directory.

> I think the sgx.trusted_files entry is not needed.

Yeah, this is not needed. GSC already collected all trusted files for you.

**Comment by nmwael** [comment] 2023-09-07 09:22
Yup with the change to "sub" paths it is working as expected, although this was never a issue with GSC or Gramine. And everything are running.

Yet again thanks @dimakuv

**Comment by mkow** [comment] 2024-05-05 14:28
@ChristopherLenz, @nmwael: Was the problem resolved? Can I close this issue, or is there something we should change/fix in Gramine?

**Comment by nmwael** [comment] 2024-05-06 11:41
> @ChristopherLenz, @nmwael: Was the problem resolved? Can I close this issue, or is there something we should change/fix in Gramine?

Please close it. Nothing to fix for you guys:)

**Closed** 2024-05-06 11:55 UTC
