### ISSUE TITLE
How to measure runtime performance overhead of gramine-sgx?

### ISSUE THREAD

**Issue by Icegrave0391** [gramineproject/gramine#1804] opened 2024-03-10 05:37 UTC
### Discussed in https://github.com/gramineproject/gramine/discussions/1803

<div type='discussions-op-text'>

<sup>Originally posted by **Icegrave0391** March 10, 2024</sup>
Hey, I'm using `gramine-sgx` enabled nodejs and I'd like to compare its performance against the native performance.

My command is:

```bash
gramine-sgx nodejs my_worklaod.js
```

However, it seems gramine-sgx will show the following message, indicating the overhead of TOML parsing is included:

```bash
Gramine is starting. Parsing TOML manifest file, this may take some time...
```

I tried to add `sex.enable_stat = true`, but it seems this will only support `perf.`  

In this case, how can I compare the workload execution (i.e., `nodejs`) runtime performance against the native performance?</div>

**Comment by mkow** [comment] 2024-03-10 10:58
Duplicate of #1803, closing. @Icegrave0391: please don't post multiple issues about exactly the same problem.

**Closed by mkow** 2024-03-10 10:58 UTC
Labels: duplicate
