### ISSUE TITLE
flock LOCK_UN

### ISSUE THREAD

**Issue by aep** [gramineproject/gramine#808] opened 2022-08-01 13:48 UTC
flock  doesnt appear to be implemented

```
ts=2022-08-01T13:40:27.058035Z lvl=info msg="Welcome to InfluxDB" log_id=0c2Q1LB0000 version=v2.3.0+SNAPSHOT.090f681737 commit=090f681737 build_date=2022-06-16T19:33:50Z
2022/08/01 13:40:27 bolt.Close(): funlock error: function not implemented
ts=2022-08-01T13:40:27.064125Z lvl=error msg="Failed opening bolt" log_id=0c2Q1LB0000 error="unable to open boltdb: function not implemented"

```

relevant code:

```go
func funlock(db *DB) error {
        return syscall.Flock(int(db.file.Fd()), syscall.LOCK_UN)
}

```

for our use case it would be ok to just return 0 and do nothing, since concurrent access doesn't really happen anyway with each process being inside its own enclave

**Comment by boryspoplawski** [comment] 2022-08-01 13:53
Duplicate of #58
@aep please comment there

**Closed by boryspoplawski** 2022-08-01 13:53 UTC
