### ISSUE TITLE
Thread not using 'expected' stack

### ISSUE THREAD

**Issue by stefanberger** [gramineproject/gramine#969] opened 2022-10-12 00:34 UTC
I am trying to hunt down an execve/robust_list-related crash on PPC64 and I am wondering whether it is intentional or a coincidence that the stack used by threads on x86_64 running into `execve` is nowhere near the one that cur_thread->stack is pointing to?

 I have instrumented a part of execve with this patch:
```
diff --git a/libos/src/sys/libos_exec.c b/libos/src/sys/libos_exec.c
index 4b43df74..d93a46f4 100644
--- a/libos/src/sys/libos_exec.c
+++ b/libos/src/sys/libos_exec.c
@@ -36,9 +36,11 @@ noreturn static void __libos_syscall_execve_rtld(void* new_argp, elf_auxv_t* new
         goto error;
     }

+    register void* sp __asm__("sp");
     struct libos_thread* cur_thread = get_cur_thread();
     for (struct libos_vma_info* vma = vmas; vma < vmas + count; vma++) {
         /* Don't free the current stack */
+        log_error("sp = %p  robus_list  %p   vma->addr=%p .. %p  stack=%p stack_red=%p", sp, cur_thread->robust_list, vma->addr, vma->addr + vma->length, cur_thread->stack, cur_thread->stack_red);
         if (vma->addr == cur_thread->stack || vma->addr == cur_thread->stack_red)
             continue;

```

When running this command

```
/usr/local/lib/x86_64-linux-gnu/gramine/direct/loader /usr/local/lib/x86_64-linux-gnu/gramine/direct/libpal.so init exec_same 1 2
```

I get this output:

```
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x400000 .. 0x401000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x600000 .. 0x601000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x601000 .. 0x602000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdad600000 .. 0x30fdad7e3000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdad7e3000 .. 0x30fdad9e3000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdad9e3000 .. 0x30fdad9e7000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdad9e7000 .. 0x30fdad9e9000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdad9e9000 .. 0x30fdad9f1000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdada00000 .. 0x30fdada01000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdada01000 .. 0x30fdadc00000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdadc00000 .. 0x30fdadc01000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdadc01000 .. 0x30fdadc02000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdadd6f000 .. 0x30fdadd70000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdadd70000 .. 0x30fdaddb0000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdaddb0000 .. 0x30fdaddb1000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdaddb1000 .. 0x30fdaddf1000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000       # Stack VMA
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdaddf1000 .. 0x30fdaddf2000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdaddf2000 .. 0x30fdade32000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdade32000 .. 0x30fdade35000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdade35000 .. 0x30fdade37000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdade37000 .. 0x30fdade38000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdade38000 .. 0x30fdade6a000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdade6a000 .. 0x30fdae06a000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdae06a000 .. 0x30fdae06c000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
[P1:T2:exec_same] error: sp = 0x7ffff3ab7b70  robus_list  0x30fdade32a20   vma->addr=0x30fdae06c000 .. 0x30fdae06e000  stack=0x30fdaddb1000 stack_red=0x30fdaddb0000
```

The stack pointer `sp` is somewhere completely different than any of the VMAs. Is this intentional? I am asking because on PPC64 I am currently doing a stack switch before calling this function because if I don't do the stackswitch then I cannot delete the VMA with the stack because the robust_list of a thread is on the stack as well and it segfaults right after the memory area has been unmapped. I later on run into robust_list related issues when in release_robust_list but that's secondary.

**Comment by boryspoplawski** [comment] 2022-10-12 00:54
LibOS has a dedicated stack. `current_thread->stack` is userspace stack, `sp` in your example is LibOS stack - these are different.
If you're familiar with x64 asm you can check this function: https://github.com/gramineproject/gramine/blob/b7feab9d19f30c2a925cedd5377c8b27da53b304/libos/src/arch/x86_64/syscallas.S#L30 it does the stack switching at the very begining.
Stack is allocated here: https://github.com/gramineproject/gramine/blob/b7feab9d19f30c2a925cedd5377c8b27da53b304/libos/src/bookkeep/libos_thread.c#L76

**Comment by stefanberger** [comment] 2022-10-12 02:32
That helped a lot. Thanks.

**Comment by stefanberger** [comment] 2022-10-12 15:58
I have changed now the stack to the libos stack. I think this resolve one issue but now I have another one related to ordering/scheduling of threads it seems. I see frequent crashes in the exec_same test on PPC64 but know it's running stable on x86_64. The headache is primarily caused due to the recent changes to exec_same where now two threads are trying to call execv(). The issue that I am seeing is related to the 'Async worker thread' calling the cleanup_thread function

https://github.com/gramineproject/gramine/blob/b7feab9d19f30c2a925cedd5377c8b27da53b304/libos/src/bookkeep/libos_thread.c#L472-L486

and then calling release_robust_list:

https://github.com/gramineproject/gramine/blob/b7feab9d19f30c2a925cedd5377c8b27da53b304/libos/src/sys/libos_futex.c#L918-L949

It tests `&head->list.next` for readablity and that passes. It ends up calling `handle_futex_death(entry_to_futex(entry, futex_offset)` and segfaults there.

The reason for the segfault *seems to be* that the 2nd thread that's going to do the `execv` ends up freeing the memory related to the robust list and futex etc. which then causes the segfault in the Async worker thread when it wakes up in `handle_futex_death`. It seems a scheduling / ordering issue that may not occur on x86_64 (unless I guess one was to put delays in the right places...).

**Comment by stefanberger** [comment] 2022-10-12 16:24
I am using this command line here:

```
/usr/local/lib/powerpc64le-linux-gnu/gramine/direct/loader /usr/local/lib/powerpc64le-linux-gnu/gramine/direct/libpal.so init exec_same 1 2 3 4 5 6 7 8 9 a b c d e f g h i j 2>&1 | tee out.txt
```

It may also be significant that if `execv` has been called 2 times it will finish to the end. In other words I see these command line runs with only '1' or '1 and 2' being printed out and then it ends or it will print all (1 2 3 4 5 ... i j) of them, basically nothing in between. It seems to have something to do with the timing of the Async worker thread startup.

**Comment by boryspoplawski** [comment] 2022-10-12 17:04
Ok, we definitely have an issue here, as you noted one thread releases whole userspace memory and another tries to handle robust futexes. Why does it not fail on x86 as well? No idea.

**Comment by boryspoplawski** [comment] 2022-10-12 17:08
I'll think about this later, but my initial thought is that we should move this robust futexes cleanups to the point where thread is still alive, should be easy.

**Comment by dimakuv** [comment] 2022-10-13 08:18
Cool data race bug! No idea why it is not triggered on x86-64; it should happen.

@boryspoplawski Isn't it better to ask the `execve`-ing thread to wait until Async thread (and possible IPC thread?) finishes with its critical sections (of executing all the pending callbacks) and allows to proceed?

Somewhere after this point: https://github.com/gramineproject/gramine/blob/63b62c4aff4ec0d59a1b715cd2163d2f1f7922eb/libos/src/sys/libos_exec.c#L177

The Async thread will take a lock (that is shared with `execve`) upon going into the loop of callbacks and release it afterwards. The `execve()` thread will wait on this lock.

Also, could similar races happen with IPC thread?

**Comment by boryspoplawski** [comment] 2022-10-13 14:37
No the problem is with using userspace memory in `put_thread`, which should only destroy Gramine internal object. All handling of userspace features (like robust futexes) should be done by the exiting thread itself, not any other threads.

> Also, could similar races happen with IPC thread?

How? IPC is Gramine internal thing, it does not handle userspace stuff (async thread shouldn't do that also, and that was the bug).

**Comment by dimakuv** [comment] 2022-10-13 15:06
Got it, thanks for the clarification about userspace vs kernel (Gramine internal) space. I didn't realize this.

**Comment by boryspoplawski** [comment] 2022-10-13 16:36
@stefanberger Could you check if https://github.com/gramineproject/gramine/pull/980 fixes the issue for you?

**Comment by stefanberger** [comment] 2022-10-13 20:32
Here's the plot for the remaining SEGFAULT (with the patches in #980 applied):

It again enters cleanup_thread but and dies after the assert(thread); likely in  `atomic_load_n()`.

I instrumented cleanup_thread like this (and also added other log_debug()s):

```
diff --git a/libos/src/bookkeep/libos_thread.c b/libos/src/bookkeep/libos_thread.c
index 3eda13baf..28ea2bfeb 100644
--- a/libos/src/bookkeep/libos_thread.c
+++ b/libos/src/bookkeep/libos_thread.c
@@ -467,20 +467,25 @@ bool check_last_thread(bool mark_self_dead) {
  * this function must follow the `void (*callback) (IDTYPE caller, void* arg)` signature. */
 void cleanup_thread(IDTYPE caller, void* arg) {
     __UNUSED(caller);
+    log_debug("%s @ %u   ENTER\n", __func__, __LINE__);

     struct libos_thread* thread = (struct libos_thread*)arg;
     assert(thread);

+    log_debug("%s @ %u   thread=%p\n", __func__, __LINE__, thread);
     /* wait on clear_child_tid_pal; this signals that PAL layer exited child thread */
     while (__atomic_load_n(&thread->clear_child_tid_pal, __ATOMIC_ACQUIRE) != 0)
         CPU_RELAX();

+    log_debug("%s @ %u\n", __func__, __LINE__);
     /* notify parent if any */
     release_clear_child_tid(thread->clear_child_tid);

+    log_debug("%s @ %u\n", __func__, __LINE__);
     /* Put down our (possibly last) reference to this thread - we got the ownership from the caller.
      */
     put_thread(thread);
+    log_debug("%s @ %u   LEAVE\n", __func__, __LINE__);
 }

 int walk_thread_list(int (*callback)(struct libos_thread*, void*), void* arg, bool one_shot) {
```

A healthy run looks like this where the libos_async_worker() does its ob before the freeing of the thread's memory:

```
[P1:T6:exec_same] debug: Installed async event at 1665688146501311
[P1:T7:exec_same] debug: Allocated stack at 0x74c959f000 (size = 0x40000)
[P1:libos] debug: Thread exited, cleaning up
[P1:libos] debug: libos_async_worker @ 345  callback at 0x7ff3e908e0   signal_alarm=0xa9be7bfd,signal_itimer=0xa9be7bfd,cleanup_thread=0x7ff3e908e0,signal_io=0xa9b67b

[P1:libos] debug: cleanup_thread @ 470   ENTER

[P1:libos] debug: cleanup_thread @ 475   thread=0x7ff3e2b020

[P1:libos] debug: cleanup_thread @ 480

[P1:libos] debug: cleanup_thread @ 484

[P1:libos] debug: cleanup_thread @ 488   LEAVE

[P1:libos] debug: libos_async_worker @ 351

[P1:libos] debug: libos_async_worker @ 356

[P1:libos] debug: Done cleaning up
[P1:T7:exec_same] debug: remove_r_debug: removing file:/usr/local/lib/aarch64-linux-gnu/gramine/tests/libos/regression/exec_same at 0
[P1:T7:exec_same] debug: remove_r_debug: removing file:/usr/local/lib/aarch64-linux-gnu/gramine/runtime/glibc/ld-linux-aarch64.so.1 at 0x74c98c1000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c962e1e0   vma->addr=0x400000 .. 0x401000  stack=0x74c959f000 stack_red=0x74c959e000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c962e1e0   vma->addr=0x410000 .. 0x411000  stack=0x74c959f000 stack_red=0x74c959e000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c962e1e0   vma->addr=0x411000 .. 0x412000  stack=0x74c959f000 stack_red=0x74c959e000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c962e1e0   vma->addr=0x74c959e000 .. 0x74c959f000  stack=0x74c959f000 stack_red=0x74c959e000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c962e1e0   vma->addr=0x74c959f000 .. 0x74c95df000  stack=0x74c959f000 stack_red=0x74c959e000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c962e1e0   vma->addr=0x74c95df000 .. 0x74c95ef000  stack=0x74c959f000 stack_red=0x74c959e000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c962e1e0   vma->addr=0x74c95ef000 .. 0x74c962f000  stack=0x74c959f000 stack_red=0x74c959e000
```

A trace that leads to the segfaults looks like this:

```
[P1:T8:exec_same] debug: Installed async event at 1665688146508198
[P1:libos] debug: Thread exited, cleaning up
[P1:T7:exec_same] debug: Allocated stack at 0x74c9670000 (size = 0x40000)
[P1:libos] debug: libos_async_worker @ 345  callback at 0x7ff3e908e0   signal_alarm=0xa9be7bfd,signal_itimer=0xa9be7bfd,cleanup_thread=0x7ff3e908e0,signal_io=0xa9b67b

[P1:libos] debug: cleanup_thread @ 470   ENTER

[P1:libos] debug: cleanup_thread @ 475   thread=0x7ff3e2b020

[P1:T7:exec_same] debug: remove_r_debug: removing file:/usr/local/lib/aarch64-linux-gnu/gramine/tests/libos/regression/exec_same at 0
[P1:T7:exec_same] debug: remove_r_debug: removing file:/usr/local/lib/aarch64-linux-gnu/gramine/runtime/glibc/ld-linux-aarch64.so.1 at 0x74c98c1000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x400000 .. 0x401000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x410000 .. 0x411000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x411000 .. 0x412000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c959e000 .. 0x74c959f000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c959f000 .. 0x74c95df000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c95ef000 .. 0x74c962f000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c966f000 .. 0x74c9670000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c9670000 .. 0x74c96b0000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c96b0000 .. 0x74c96c0000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c96c0000 .. 0x74c9700000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c9700000 .. 0x74c987c000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c987c000 .. 0x74c988c000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c988c000 .. 0x74c988f000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c988f000 .. 0x74c9892000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c9892000 .. 0x74c9899000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98a0000 .. 0x74c98a1000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98a1000 .. 0x74c98b0000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98b0000 .. 0x74c98b1000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98b1000 .. 0x74c98b2000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98bc000 .. 0x74c98be000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98be000 .. 0x74c98c0000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98c0000 .. 0x74c98c1000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98c1000 .. 0x74c98eb000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98eb000 .. 0x74c98fa000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98fa000 .. 0x74c98fc000  stack=0x74c9670000 stack_red=0x74c966f000
[P1:T7:exec_same] debug: sp = 0x7ff3e21d00  robus_list  0x74c98bc100   vma->addr=0x74c98fc000 .. 0x74c98fe000  stack=0x74c9670000 stack_red=0x74c966f000
```

Obviously it did not finish the cleanup_thread() in this case...

**Comment by stefanberger** [comment] 2022-10-13 20:34
oh and now you know something else as well...

**Comment by stefanberger** [comment] 2022-10-13 21:59
The trouble seem to start with this: Upon thread_exit install_async_event() is called which calls set_pollable_event() in the end which in turn wants to write a byte to a pipe. For some reason it gets stuck writing this single byte to the pipe occasionally and then things go bad. It looks like nothing is ever reading from this pipe, at least not though the pipe_read function (pal/src/host/linux/pal_pipes.c).

**Comment by boryspoplawski** [comment] 2022-10-13 23:32
Huh, weird. Can you run this under GDB/strace and see the crash location and faulting address?

**Comment by stefanberger** [comment] 2022-10-14 16:20
I think I found it. It looks like it's not an issue for x86_64 but nevertheless ...

To repeat, the problem: The problem is in the exec_same test program where one thread looses the competition for running `execve()`. The loosing thread has to reset its pointer to the thread local storage (TLS) area from the one that glibc may have set to the the default one (set_default_tls() ) because the winning thread is going to tear down the memory that represents the (glibc-allocated) TLS and once that has happened the loosing thread(s) must never access the TLS. So I have now added set_default_tls() into thread_exit() like this.

```
noreturn void thread_exit(int error_code, int term_signal) {
    set_default_tls();

    struct libos_thread* cur_thread = get_cur_thread();
    if (cur_thread->robust_list) {
        release_robust_list(cur_thread->robust_list);
        cur_thread->robust_list = NULL;
    }

    /* Remove current thread from the threads list. */
    if (!check_last_thread(/*mark_self_dead=*/true)) {
        /* ask async worker thread to cleanup this thread */
```

This seems to fix it and the test case runs fine now. But I am wondering if it may not work in all cases because if the loosing thread was really slow and the winner already freed the memory then get_cur_thread() anywhere in the code [without the prior set_default_tls()] would cause the same problem again in the loosing thread(s). So. I would think that all the siblings of the loosing thread would have to terminate first before the winner frees the memory, but this is likely not a desirable requirement that they all need to terminate. So maybe I am missing something as to how x86_64 gets around this... (maybe the TLS is in other memory or on the stack?)

**Comment by stefanberger** [comment] 2022-10-14 18:21
It feels like in the `execve` case (or any other case where a thread frees all memory) the winning thread has to send an inter-thread-interrupt to tell its siblings to terminate... otherwise it may end up even freeing code or data pages that its siblings are currently touching.

**Comment by boryspoplawski** [comment] 2022-10-14 18:56
Oh, that's tough. In x64 we have custom Gramine TLS, which is fully managed by Gramine and completely separate end unrelated to glibc TLS. Generally whole Gramine operates on the assumption that this TLS/TCB is private to Gramine and not shared with "userspace".

**Comment by stefanberger** [comment] 2022-10-14 19:36
I remembered that at some point and it didn't matter so far. Now it does ...

Do you think the robust list fix in #980 is correct and also needed on x86_64 modulo the current ltp test case error? I am trying to figure out whether I can assume that this fix is correct or I have to somehow figure out what's wrong assuming it will not be merged ...

**Comment by boryspoplawski** [comment] 2022-10-14 22:47
Yes, it will definitely be merged and is needed on x64 too (I just need to fix that one error, already debugged, just need to create a proper solution, probably on monday)

**Comment by boryspoplawski** [comment] 2022-10-14 22:54
BTW
> This seems to fix it and the test case runs fine now. But I am wondering if it may not work in all cases because if the loosing thread was really slow and the winner already freed the memory then get_cur_thread() anywhere in the code [without the prior set_default_tls()] would cause the same problem again in the loosing thread(s). So. I would think that all the siblings of the loosing thread would have to terminate first before the winner frees the memory, but this is likely not a desirable requirement that they all need to terminate

It's already the case. This function is called before any memory is freed: https://github.com/gramineproject/gramine/blob/master/libos/src/sys/libos_exit.c#L132 and it ensures that thread is already past this point: https://github.com/gramineproject/gramine/blob/master/libos/src/sys/libos_exit.c#L67
On x64 that's enough, because we know that thread can never return to userspace and only uses Gramine internal stuff now. On ppc that's not the case though, since you have Gramine TLS in userspace memory...

**Comment by stefanberger** [comment] 2022-10-15 00:49
> On x64 that's enough, because we know that thread can never return to userspace and only uses Gramine internal stuff now. On ppc that's not the case though, since you have Gramine TLS in userspace memory...

So this here seems to resolve the issue -- exec_same test case has been running rock-solid for hours now:

````
diff --git a/libos/src/sys/libos_exit.c b/libos/src/sys/libos_exit.c
index 96ebc2645..05dc8dbd9 100644
--- a/libos/src/sys/libos_exit.c
+++ b/libos/src/sys/libos_exit.c
@@ -63,6 +63,13 @@ static noreturn void libos_clean_and_exit(int exit_code) {
 }

 noreturn void thread_exit(int error_code, int term_signal) {
+#if defined(__powerpc64__)
+    /* Need to get rid of possible glibc-allocated TLS because a concurrent
+     * thread may be releasing all the memory, including the TLS memory.
+     */
+    set_default_tls();
+#endif
+
     struct libos_thread* cur_thread = get_cur_thread();
     if (cur_thread->robust_list) {
         release_robust_list(cur_thread->robust_list);
```

**Comment by boryspoplawski** [comment] 2022-10-15 01:19
How is `get_cur_thread` implemented on ppc64? Doesn't it need valid TLS?

**Comment by stefanberger** [comment] 2022-10-15 02:10
I do some trickery with pointers here. At the beginning the PAL_TCB is installed and when glibc comes along and wants to install its TLS I let it do that but also install a pointer from the TLS to the previous PAL_TCB. When set_default_tls() is called I look for that original PAL_TCB pointer and have that again as the TLS and can then discard the glibc TLS.

**Closed** 2022-10-19 12:11 UTC
